force-app/main/default/objects/SObjectTriggerSetting__mdt/SObjectTriggerSetting__mdt.object-meta.xml
<CustomObject>
    <description>SObject Trigger Setting</description>
    <label>SObject Trigger Setting</label>
    <pluralLabel>SObject Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SObjectTriggerSetting__mdt/fields/ObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPIName__c</fullName>
    <description>Enter the API Name of the object for this trigger. Include Package prefix.</description>
    <inlineHelpText>Enter the API Name of the object for this trigger. Include Package prefix.</inlineHelpText>
    <label>Object Api Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SObjectTriggerSetting__mdt/fields/RecursionCount__c.field-meta.xml
<CustomField>
    <fullName>RecursionCount__c</fullName>
    <description>Recursion count for SObject trigger</description>
    <inlineHelpText>Recursion count for SObject trigger</inlineHelpText>
    <label>RecursionCount</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SObjectTriggerSetting__mdt/fields/TriggerHandlerName__c.field-meta.xml
<CustomField>
    <fullName>TriggerHandlerName__c</fullName>
    <description>Trigger handler name to invoke</description>
    <inlineHelpText>Trigger handler name to invoke</inlineHelpText>
    <label>Trigger Handler Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/test/default/classes/TriggerDispatcherTest.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Test
 * @author Digital Align Team
 * @reference
 * @description
 **/
@IsTest
public with sharing class TriggerDispatcherTest {
  @IsTest
  private static void triggerHanlder() {
    String handlerName = 'AccountTriggerHandler';
    SObjectTriggerSetting__mdt triggerSetting = new SObjectTriggerSetting__mdt();
    triggerSetting.ObjectAPIName__c = 'Account';
    triggerSetting.TriggerHandlerName__c = 'AccountTriggerHandler';
    triggerSetting.RecursionCount__c = 4;

    TriggerDispatcher.run(Account.SObjectType);
    TriggerDispatcher.executeTriggerAction(triggerSetting, null);
    TriggerDispatcher.setMaxLoopCount(handlerName, 4);
    TriggerDispatcher.validateRun(handlerName);
    TriggerDispatcher.validateRun('Random');
    TriggerDispatcher.removeFromLoopCount(handlerName);
    TriggerDispatcher.bypass(handlerName);
    TriggerDispatcher.clearBypass(handlerName);
    TriggerDispatcher.isBypassed(handlerName);
    TriggerDispatcher.clearAllBypasses();
    TriggerDispatcher.loopCountMap.get(handlerName).setMax(4);
    TriggerDispatcher.loopCountMap.get(handlerName).increment();
    TriggerDispatcher.loopCountMap.get(handlerName).decrement();
    TriggerDispatcher.loopCountMap.get(handlerName).getCount();
    system.assertEquals(
      false,
      TriggerDispatcher.loopCountMap.get(handlerName).exceeded()
    );
  }
}