force-app/main/default/objects/Flow__c/Flow__c.object-meta.xml
<CustomObject>
    <description>Transition flow for any applciation purpose</description>
    <label>Flow</label>
    <nameField>
        <displayFormat>Flow-{00000}</displayFormat>
        <label>Flow Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flow__c/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to link the sub flow to flow</description>
    <inlineHelpText>Used to link the sub flow to flow</inlineHelpText>
    <label>Flow</label>
    <referenceTo>Flow__c</referenceTo>
    <relationshipLabel>Sub Flows</relationshipLabel>
    <relationshipName>SubFlows</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flow__c/recordTypes/Flow.recordType-meta.xml
<RecordType>
    <fullName>Flow</fullName>
    <active>true</active>
    <description>Parent flow record type</description>
    <label>Flow</label>
</RecordType>

force-app/main/default/classes/LwcCustomRepository.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Repository
 * @author Digital Align Team
 * @reference
 * @description
 **/
public with sharing class LwcCustomRepository extends DatabaseUtils {
  /**
   * @description fetch existing flow from entity
   * @author Digital Align Team | 10-19-2021
   * @param String entityId
   * @return List<Flow__c>
   **/
  public static List<Flow__c> fetchFlowByEntityId(String entityId) {
    String q = Query.newInstance(Flow__c.SObjectType)
      .addFields()
      .queryChild('mflow__SubFlows__r')
      .addFields()
      .run()
      .whereEq('mflow__Entity__c', entityId)
      .toString();
    return (List<Flow__c>) getRecords(q);
  }
}