force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>Object to capture dealer onboarding questions</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/isDisplayed__c.field-meta.xml
<CustomField>
    <fullName>isDisplayed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be Showed in Layout</description>
    <inlineHelpText>To be Showed in Layout</inlineHelpText>
    <label>isDisplayed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/LongDescription__c.field-meta.xml
<CustomField>
    <fullName>LongDescription__c</fullName>
    <description>Complete survey question</description>
    <label>Long Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/OptionType__c.field-meta.xml
<CustomField>
    <fullName>OptionType__c</fullName>
    <description
  >Type of the question Text/ Sub Question/ Dependent question</description>
    <label>Option Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/ParentQuestionCode__c.field-meta.xml
<CustomField>
    <fullName>ParentQuestionCode__c</fullName>
    <description>Related question code</description>
    <label>Parent Question Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/QuestionNumber__c.field-meta.xml
<CustomField>
    <fullName>QuestionNumber__c</fullName>
    <label>Question Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/ShortDescription__c.field-meta.xml
<CustomField>
    <fullName>ShortDescription__c</fullName>
    <description
  >alternate text for original question if it exceeds length 255</description>
    <label>Short Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/ShowQuestionNumber__c.field-meta.xml
<CustomField>
    <fullName>ShowQuestionNumber__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show Question Number</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/SurveyTemplateItem__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplateItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SurveyTemplate Item</label>
    <referenceTo>SurveyTemplateItem__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/TemplateName__c.field-meta.xml
<CustomField>
    <fullName>TemplateName__c</fullName>
    <description>Mathcing Template Name</description>
    <inlineHelpText>Mathcing Template Name</inlineHelpText>
    <label>Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/SurveyTemplate__c.object-meta.xml
<CustomObject>
    <label>SurveyTemplate</label>
    <nameField>
        <label>SurveyTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SurveyTemplate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateItem__c/SurveyTemplateItem__c.object-meta.xml
<CustomObject>
    <label>Survey Template Item</label>
    <nameField>
        <label>Survey TemplateItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateItem__c/fields/CustomStyle__c.field-meta.xml
<CustomField>
    <fullName>CustomStyle__c</fullName>
    <description>Custom CSS Style for your survey</description>
    <inlineHelpText>Custom CSS Style for your survey</inlineHelpText>
    <label>Custom Style</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/fields/hasChild__c.field-meta.xml
<CustomField>
    <fullName>hasChild__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Question Has Sub Question Related</description>
    <inlineHelpText>Question Has Sub Question Related</inlineHelpText>
    <label>hasChild</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/fields/ShortDescription__c.field-meta.xml
<CustomField>
    <fullName>ShortDescription__c</fullName>
    <label>Short Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Items</relationshipLabel>
    <relationshipName>SurveyTemplateItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SurveyResolver.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Resolver
 * @author Digital Align Team
 * @reference
 * @description
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global with sharing class SurveyResolver extends AbstractService {
  @TestVisible
  private static SurveyResolver serviceInstance;

  public SurveyResolver() {
    super(SurveyResolver.class);
  }

  /**
   * @description Provides a singleton instance of SurveyResolver from which all other class methods can be accessed.
   * @author Digital Align Team | 07-22-2021
   * @return Object  singleton
   **/
  public static SurveyResolver getInstance() {
    if (serviceInstance == null) {
      serviceInstance = (SurveyResolver) getInstance(SurveyResolver.class);
    }
    return serviceInstance;
  }

  /**
   * @description fetch survey by filters
   * @author Digital Align | 12-22-2021
   * @param List<Object> filters
   * @return virtual
   **/
  global virtual List<Survey__c> fetchSurvey(List<Object> filters) {
    List<SurveyTemplate__c> surveyTemlates = SurveyRepository.fetchSurveyTemplateByFilters(
      filters
    );
    return buildSurvey(surveyTemlates);
  }

  /**
   * @description build survey object based on the template list
   * @author Digital Align Team | 08-25-2021
   * @param List<SurveyTemplate__c> surveyTemlates
   * @return List<Survey__c>
   **/
  global virtual List<Survey__c> buildSurvey(
    List<SurveyTemplate__c> surveyTemlates
  ) {
    List<Survey__c> surveyList = new List<Survey__c>();
    for (SurveyTemplate__c surveyTemplate : surveyTemlates) {
      for (SurveyTemplateItem__c item : surveyTemplate.SurveyTemplateItems__r) {
        Survey__c surveyObj = new Survey__c();
        surveyObj.OptionType__c = item.OptionType__c;
        surveyObj.ParentQuestionCode__c = item.ParentQuestionCode__c;
        surveyObj.QuestionCode__c = item.QuestionCode__c;
        surveyObj.QuestionNumber__c = item.QuestionNumber__c;
        surveyObj.ShortDescription__c = item.ShortDescription__c;
        surveyObj.LongDescription__c = item.LongDescription__c;
        surveyObj.ShowQuestionNumber__c = item.ShowQuestionNumber__c;
        surveyObj.Condition__c = item.Condition__c;
        surveyObj.hasChild__c = item.hasChild__c;
        surveyObj.CustomStyle__c = item.CustomStyle__c;
        surveyObj.Order__c = item.Order__c;
        surveyObj.Options__c = item.Options__c;
        surveyObj.Name = item.Name;
        surveyObj.TemplateName__c = surveyTemplate.Name;
        if (String.isBlank(item.ParentQuestionCode__c)) {
          surveyObj.isDisplayed__c = true;
        } else {
          surveyObj.isDisplayed__c = false;
        }
        surveyList.add(surveyObj);
      }
    }
    return surveyList;
  }
}