force-app/main/default/objects/Account/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application for grorup MintFlow related details</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IdentificationDocument__c.field-meta.xml
<CustomField>
    <fullName>IdentificationDocument__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Object to store all identity details</description>
    <label>Identification Document</label>
    <referenceTo>FinServ__IdentificationDocument__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/PrimaryAddress__c.field-meta.xml
<CustomField>
    <fullName>PrimaryAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Address</label>
    <referenceTo>ContactPointAddress</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationConfiguration__c/ApplicationConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Configuration</label>
</CustomObject>

force-app/main/default/objects/ContactPointAddress/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and contact point address</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Contact Point Addresses</relationshipLabel>
    <relationshipName>ContactPointAddresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employment__c/Employment__c.object-meta.xml
<CustomObject>
    <description
  >Represents information about a person&apos;s employment history.</description>
    <label>Employment</label>
    <nameField>
        <displayFormat>Emp-{00000}</displayFormat>
        <label>Employment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/FinancialAccount__c.object-meta.xml
<CustomObject>
    <description
  >A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Financial Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DAT-200</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>related product</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccountTransaction__c/FinancialAccountTransaction__c.object-meta.xml
<CustomObject>
    <description
  >Represents information about financial account transactions.</description>
    <label>Financial Account Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccountTransaction__c/fields/FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Financial Account</description>
    <label>Financial Account</label>
    <referenceTo>FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Transactions</relationshipLabel>
    <relationshipName>FinancialAccountTranslations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialProduct__c/FinancialProduct__c.object-meta.xml
<CustomObject>
    <description>Object to store all product related data</description>
    <label>Financial Product</label>
    <nameField>
        <label>FinancialProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/FinServ__Employment__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__EmploymentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about a person&apos;s employment history.</description>
    <label>Employment</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and Employment realtionship</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Employment</relationshipLabel>
    <relationshipName>Employments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description
  >A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fiancial Account relationship with Account</description>
    <label>Application</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts (Application)</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>related product</description>
    <label>FinancialProduct</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

fsc-app/main/default/objects/FinServ__IdentificationDocument__c/FinServ__IdentificationDocument__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__IdentificationDocumentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about documents used to verify a person&apos;s identity.</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>DOC-{000000000}</displayFormat>
        <label>Document</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IdentificationDocument__c/IdentificationDocument__c.object-meta.xml
<CustomObject>
    <description>Identification Document for Applicants</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/test/default/classes/LwcCustomServiceTest.cls
@istest
public with sharing class LwcCustomServiceTest {
  //makeApplicationConfiguration
  private static void makeApplicationConfiguration() {
    ApplicationConfiguration__c appConfig = TestData.createApplicationConfiguration();
    insert appConfig;
    TestData.createSiteSetting();
    List<FinancialProduct__c> products = TestData.createProduct();
    insert products;
  }
  //createApplicantDataWithChild
  private static Applicant__c createApplicantDataWithChild(Application__c application) {
    Applicant__c applicant = Application.Applicants__r[0];
    SObjectConstructor construct = SObjectConstructor.getInstance(applicant);

    IdentificationDocument__c identity = TestData.createIdentity(applicant.Id);
    insert identity;

    Employment__c employment = TestData.createEmployment(applicant.Id);
    insert employment;

    ContactPointAddress address = TestData.createContactPointAddress(applicant.Id);
    insert address;

    construct.addChildObject('mflow__IdentificationDocuments__r', identity);
    construct.addChildObject('mflow__Employments__r', employment);
    construct.addChildObject('mflow__ContactPointAddresses__r', address);

    return (Applicant__c) construct.build();
  }
  //createApplicantDataWithChild
  private static FinancialAccount__c createFinancialAccountWithChild(Application__c application) {
    FinancialAccount__c finAccount = Application.FinancialAccounts__r[0];
    SObjectConstructor construct = SObjectConstructor.getInstance(finAccount);

    FinancialAccountTransaction__c finTransaction = TestData.createFinancialAccountTransaction(finAccount.Id);
    insert finTransaction;

    construct.addChildObject('FinancialAccountTransactions__r', finTransaction);
    return (FinancialAccount__c) construct.build();
  }
  @istest
  private static void readFlowsTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);

    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    Map<String, String> params = new Map<String, String>();

    ApexResponse res = LwcCustomController.readFlows(params);
    system.assertEquals(200, res.status, 'success');

    request = new ApexRequest();
    LwcCustomController.readFlows(params);
  }

  @istest
  private static void fetchConfigValuesTest() {
    makeApplicationConfiguration();
    ApexResponse res = LwcCustomController.fetchConfigValues();
    system.assertEquals(200, res.status, 'success');
  }
  @istest
  private static void updateConfigValuesTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);

    Map<String, String> params = new Map<String, String>();
    params.put('configData', '{\"mflow__OOWTotalQuestionsToShow__c\":5}');
    ApexResponse res = LwcCustomController.updateConfigValues(params);
  }

  @istest
  private static void readApplicationWithChildTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);

    ApexResponse res = LwcCustomController.readApplicationWithChild(application.Id);
    System.assertEquals(200, res.status, 'success');
    res = LwcCustomController.readApplicationWithChild(applicant.Id);
    System.assertEquals(400, res.status, 'success');
  }

  @istest
  private static void readApplicationWithApplicantsTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);

    ApexResponse res = LwcCustomController.readApplicationWithApplicants(application.Id);
    System.assertEquals(200, res.status, 'success');
    res = LwcCustomController.readApplicationWithApplicants('');
    System.assertEquals(400, res.status, 'success');
  }

  @istest
  private static void readApplicationForResumeTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);

    Map<String, String> params = new Map<String, String>();
    params.put('recordId', applicant.Id);
    ApexResponse res = LwcCustomController.readApplicationForResume(params);
    System.assertEquals(400, res.status, 'success');

    params.put('recordId', application.Id);
    res = LwcCustomController.readApplicationForResume(params);
    System.assertEquals(200, res.status, 'success');
  }

  @istest
  private static void sendResumeApplicationEmailTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);

    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setData(JSON.serialize(new List<Id>{ applicant.Id }));
    ApexResponse res = LwcCustomController.sendResumeApplicationEmail(request);
    System.assertEquals(200, res.status, 'success');

    request = new ApexRequest();
    request.token = 'Invalid token';
    res = LwcCustomController.sendResumeApplicationEmail(request);
    System.assertEquals(400, res.status, 'success');
  }

  @istest
  private static void fetchFieldDetailsTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);

    Map<String, String> params = new Map<String, String>();
    params.put('sObjectName', 'mflow__Applicant__c');
    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setData(JSON.serialize(new List<Id>{ applicant.Id }));
    ApexResponse res = LwcCustomController.fetchFieldDetails(params);
    System.assertEquals(200, res.status, 'success');

    params.put('fieldSetName', 'mflow__ContactInformation');
    request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setData(JSON.serialize(new List<Id>{ applicant.Id }));
    res = LwcCustomController.fetchFieldDetails(params);
    System.assertEquals(200, res.status, 'success');

    request = new ApexRequest();
    request.token = 'Invalid token';
    res = LwcCustomController.fetchFieldDetails(null);
    System.assertEquals(400, res.status, 'success');
  }

  @istest
  private static void fetchPickListValuesTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);

    Map<String, Object> params = new Map<String, Object>();
    params.put('Lead', new List<string>{ 'LeadSource', 'Staus' });
    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setData(JSON.serialize(new List<Id>{ applicant.Id }));
    ApexResponse res = LwcCustomController.fetchPickListValues(params);
    System.assertEquals(400, res.status, 'success');
  }
  @istest
  private static void updateKycDecisionTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);

    //Applicant
    Map<String, Object> params = new Map<String, Object>();
    params.put('recordId', application.mflow__Applicants__r[0].Id);
    params.put('objectApiName', 'mflow__Applicant__c');
    params.put('status', 'Passed');
    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setData(JSON.serialize(new List<Id>{ applicant.Id }));
    ApexResponse res = LwcCustomController.updateKycDecision(params);
    System.assertEquals(200, res.status, 'success');

    params.put('status', ApplicationConstant.KYC_FAILED);
    res = LwcCustomController.updateKycDecision(params);
    System.assertEquals(200, res.status, 'success');

    //Application
    params = new Map<String, Object>();
    params.put('recordId', application.Id);
    params.put('objectApiName', 'mflow__Application__c');
    params.put('status', 'Passed');
    request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setData(JSON.serialize(new List<Id>{ applicant.Id }));
    res = LwcCustomController.updateKycDecision(params);
    System.assertEquals(200, res.status, 'success');

    params.put('status', ApplicationConstant.KYC_FAILED);
    res = LwcCustomController.updateKycDecision(params);
    System.assertEquals(200, res.status, 'success');

    // other object type
    params.put('objectApiName', 'Account');
    res = LwcCustomController.updateKycDecision(params);
    System.assertEquals(400, res.status, 'success');
  }
  @istest
  private static void fetchRelatedFilesTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);

    ApexResponse res = LwcCustomController.fetchRelatedFiles(JSON.serialize(new List<String>{ applicant.Id }));
    System.assertEquals(200, res.status, 'success');

    res = LwcCustomController.fetchRelatedFiles('string');
    System.assertEquals(400, res.status, 'success');
  }
  @istest
  private static void resubmitApplicationTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);
    // FinancialAccount__c finAcc = createFinancialAccountWithChild(application);

    ApexResponse res = LwcCustomController.resubmitApplication(application.Id);
    System.assertEquals(200, res.status, 'success');

    res = LwcCustomController.resubmitApplication(null);
    System.assertEquals(400, res.status, 'success');
  }
  // request.setHeader(new Map<String, object>{ 'applicantIds' => application.mflow__Applicants__r });
  // request.setData(new List<Id>{ application.Id });
  // params.put('recordId', application.mflow__Applicants__r[0].Id);
  // params.put('objectApiName', 'mflow__Applicant__c');
  // params.put('status', 'Passed');
  // params.put('approvalType', 'approvalType');
  // // params.put(arg0, arg1);
  // LwcCustomController.fetchFieldDetails(params);
  // LwcCustomController.fetchFieldDetails(params);
  // LwcCustomController.updateKycDecision(params);

  // @istest
  // private static void readFlowsTestTwo() {
  //   Application__c acc = TestData.createApplication();
  //   Map<String, Object> params = new Map<String, Object>();
  //   params.put('Lead', new List<string>{ 'LeadSource', 'Staus' });
  //   params.put('sObjectName', 'Account');
  //   params.put('fieldSetName', 'fieldSetName');
  //   makeApplicationConfiguration();
  //   test.startTest();
  //   try {
  //     LwcCustomController.resubmitApplication(acc.Id);
  //   } catch (Exception e) {
  //   }
  //   test.stopTest();
  // }
  // @istest
  // private static void readFlowsTestThree() {
  //   Application__c acc = TestData.createApplication();
  //   Map<String, Object> params = new Map<String, Object>();
  //   params.put('Lead', new List<string>{ 'LeadSource', 'Staus' });
  //   params.put('sObjectName', 'Account');
  //   params.put('fieldSetName', 'fieldSetName');
  //   makeApplicationConfiguration();
  //   LwcCustomController.fetchRelatedFiles(JSON.serialize(new List<String>{ acc.Id }));
  // }
  // @istest
  // private static void authorizeCustomerTest() {
  //   Application__c acc = makeApplicationData();
  //   acc = TestData.readApplicationWithChild(acc.Id);
  //   Map<String, Object> params = new Map<String, Object>();
  //   makeApplicationConfiguration();
  //   ApexResponse res = new ApexResponse();
  //   //400
  //   params.put('applicant', new Applicant__c());
  //   res = LwcCustomController.authorizeCustomer(params);
  //   system.assertEquals(400, res.status, 'success');
  //   //200
  //   params.put('applicant', acc.mflow__Applicants__r[0]);
  //   res = LwcCustomController.authorizeCustomer(params);
  //   system.assertEquals(200, res.status, 'success');

  //   params.remove('applicant');
  //   res = LwcCustomController.authorizeCustomer(params);
  // }
  // @istest
  // private static void lwcRecordLevelVisibilityTest() {
  //   Application__c acc = makeApplicationData();
  //   acc = TestData.readApplicationWithChild(acc.Id);
  //   Map<String, Object> params = new Map<String, Object>();
  //   makeApplicationConfiguration();
  //   ApexResponse res = new ApexResponse();
  //   //400
  //   params.put('recordId', acc.mflow__Applicants__r[0].Id);
  //   params.put('objectApiName', 'mflow__Applicant__c');
  //   params.put('filter', 'filter');
  //   res = LwcCustomController.lwcRecordLevelVisibility(params);
  //   // system.assertEquals(400, res.status, 'success');
  //   // //200
  //   // params.put('applicant', acc.mflow__Applicants__r[0]);
  //   // res = LwcCustomController.authorizeCustomer(params);
  //   // system.assertEquals(200, res.status, 'success');

  //   // params.remove('applicant');
  //   // res = LwcCustomController.authorizeCustomer(params);
  // }
  // @istest
  // private static void readFlowsTestFour() {
  //   Application__c acc = TestData.createApplication();
  //   Map<String, Object> params = new Map<String, Object>();
  //   params.put('Lead', new List<string>{ 'LeadSource', 'Staus' });
  //   params.put('sObjectName', 'Account');
  //   params.put('fieldSetName', 'fieldSetName');
  //   makeApplicationConfiguration();
  //   test.startTest();
  //   try {
  //     LwcCustomController.fetchOOWReportData(acc.Id);
  //   } catch (Exception e) {
  //   }
  //   test.stopTest();
  // }
  // @istest
  // private static void readFlowsTestSix() {
  //   Application__c acc = TestData.createApplication();
  //   Map<String, string> params = new Map<String, string>();
  //   params.put('sObjectName', 'Account');
  //   params.put('fieldSetName', 'fieldSetName');
  //   makeApplicationConfiguration();
  //   test.startTest();
  //   try {
  //     LwcCustomController.fetchFieldDetails(params);
  //   } catch (Exception e) {
  //   }
  //   test.stopTest();
  // }
  // @istest
  // private static void readFlowsTestSeven() {
  //   Application__c acc = TestData.createApplication();
  //   acc = TestData.readApplicationWithChild(acc.Id);
  //   Map<String, string> params = new Map<String, string>();
  //   params.put('sObjectName', 'Account');
  //   params.put('fieldSetName', 'fieldSetName');
  //   makeApplicationConfiguration();
  //   test.startTest();
  //   try {
  //     LwcCustomController.fetchFieldDetails(params);
  //   } catch (Exception e) {
  //   }
  //   test.stopTest();
  // }
  // @istest
  // private static void sendResumeApplicationEmailTest() {
  //   Application__c application = makeApplicationData();
  //   application = TestData.readApplicationWithChild(application.Id);
  //   ApexRequest request = new ApexRequest();
  //   Map<String, object> params = new Map<String, object>();
  //   params.put('Lead', new List<string>{ 'LeadSource', 'Staus' });
  //   params.put('sObjectName', 'mflow__Application__c');
  //   params.put('fieldSetName', 'fieldSetName');
  //   request.setHeader(new Map<String, object>{ 'applicantIds' => application.mflow__Applicants__r });
  //   request.setData(new List<Id>{ application.mflow__Applicants__r[0].Id });
  //   makeApplicationConfiguration();

  //   ApexResponse res = LwcCustomController.sendResumeApplicationEmail(request);
  //   //500
  //   request = new ApexRequest();
  //   request.token = 'invalidToken';
  //   res = LwcCustomController.sendResumeApplicationEmail(request);
  //   system.assertEquals(500, res.status, 'success');
  // }
  // @istest
  // private static void TestEleven() {
  //   Application__c application = makeApplicationData();
  //   application = TestData.readApplicationWithChild(application.Id);
  //   ApexRequest request = new ApexRequest();
  //   Map<String, object> params = new Map<String, object>();
  //   params.put('Lead', new List<string>{ 'LeadSource', 'Staus' });
  //   params.put('sObjectName', 'mflow__Application__c');
  //   params.put('fieldSetName', 'fieldSetName');
  //   request.setHeader(new Map<String, object>{ 'applicantIds' => application.mflow__Applicants__r });
  //   request.setData(new List<Id>{ application.mflow__Applicants__r[0].Id });
  //   makeApplicationConfiguration();
  //   LwcCustomController.fetchPickListValues(params);
  // }
  // @istest
  // private static void TestNine() {
  //   Application__c application = makeApplicationData();
  //   application = TestData.readApplicationWithChild(application.Id);
  //   ApexRequest request = new ApexRequest();
  //   Map<String, object> params = new Map<String, object>();
  //   params.put('Lead', new List<string>{ 'LeadSource', 'Staus' });
  //   params.put('objectApiName', 'mflow__Application__c');
  //   params.put('fieldSetName', 'fieldSetName');
  //   params.put('approvalType', 'Application');
  //   params.put('status', ApplicationConstant.KYC_PASSED);
  //   params.put('recordId', application.Id);
  //   request.setHeader(new Map<String, object>{ 'applicantIds' => application.mflow__Applicants__r });
  //   request.setData(new List<Id>{ application.mflow__Applicants__r[0].Id });
  //   makeApplicationConfiguration();
  //   LwcCustomController.updateKycDecision(params);
  //   params.put('approvalType', 'Application And Applicants');
  //   params.put('status', ApplicationConstant.KYC_FAILED);
  //   LwcCustomController.updateKycDecision(params);
  // }
  // @istest
  // private static void TestTen() {
  //   Application__c application = makeApplicationData();
  //   application = TestData.readApplicationWithChild(application.Id);
  //   ApexRequest request = new ApexRequest();
  //   Map<String, object> params = new Map<String, object>();
  //   params.put('Lead', new List<string>{ 'LeadSource', 'Staus' });
  //   params.put('objectApiName', 'mflow__Application__c');
  //   params.put('fieldSetName', 'fieldSetName');
  //   params.put('approvalType', 'Application');
  //   params.put('status', ApplicationConstant.KYC_FAILED);
  //   params.put('recordId', application.Id);
  //   request.setHeader(new Map<String, object>{ 'applicantIds' => application.mflow__Applicants__r });
  //   request.setData(new List<Id>{ application.mflow__Applicants__r[0].Id });
  //   makeApplicationConfiguration();
  //   LwcCustomController.updateKycDecision(params);
  //   params.put('approvalType', 'Application And Applicants');
  //   params.put('status', ApplicationConstant.KYC_PASSED);
  //   LwcCustomController.updateKycDecision(params);
  // }
  // @istest
  // private static void TestTwelve() {
  //   Application__c application = makeApplicationData();
  //   application = TestData.readApplicationWithChild(application.Id);
  //   ApexRequest request = new ApexRequest();
  //   Map<String, object> params = new Map<String, object>();
  //   params.put('filter', 'filter');
  //   params.put('recordId', application.mflow__Applicants__r[0].Id);
  //   request.setHeader(new Map<String, object>{ 'applicantIds' => application.mflow__Applicants__r });
  //   request.setData(new List<Id>{ application.mflow__Applicants__r[0].Id });
  //   makeApplicationConfiguration();
  //   LwcCustomController.readApplicationForResume(params);
  // }
}