force-app/main/default/objects/Account/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application for grorup MintFlow related details</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/IdentificationDocument__c.field-meta.xml
<CustomField>
    <fullName>IdentificationDocument__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Object to store all identity details</description>
    <label>Identification Document</label>
    <referenceTo>FinServ__IdentificationDocument__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__Employment__c/FinServ__Employment__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__EmploymentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about a person&apos;s employment history.</description>
    <label>Employment</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and Employment realtionship</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Employment</relationshipLabel>
    <relationshipName>Employments</relationshipName>
    <type>Lookup</type>
</CustomField>

fsc-app/main/default/objects/FinServ__IdentificationDocument__c/FinServ__IdentificationDocument__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__IdentificationDocumentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about documents used to verify a person&apos;s identity.</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>DOC-{000000000}</displayFormat>
        <label>Document</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IdentificationDocument__c/IdentificationDocument__c.object-meta.xml
<CustomObject>
    <description>Identification Document for Applicants</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApplicationFileApi.cls
public with sharing class ApplicationFileApi {
  private static logger log = logger.getInstance(ApplicationDataAPI.class);
  public static ApexResponse obtainApplicationData(string applicationId) {
    if (string.isBlank(applicationId)) {
      throw new CustomException('Application value is not set');
    }
    List<id> reletedEntityIdList = new List<id>();
    List<ContentVersion> fileList = new List<ContentVersion>();
    try {
      Account application = ApplicationService.getInstance()
        .readApplicationWithChild(applicationId);

      for (Applicant__c applicant : application.mflow__Applicants__r) {
        // documents related to applicant
        reletedEntityIdList.add(applicant.Id);
        if (!CollectionUtils.isListEmpty(applicant.mflow__Employments__r)) {
          //Employment documents
          for (
            FinServ__Employment__c employment : applicant.mflow__Employments__r
          ) {
            reletedEntityIdList.add(employment.Id);
          }
        }
        if (
          !CollectionUtils.isListEmpty(
            applicant.mflow__IdentificationDocuments__r
          )
        ) {
          //Identity documents
          for (
            FinServ__IdentificationDocument__c identity : applicant.mflow__IdentificationDocuments__r
          ) {
            reletedEntityIdList.add(identity.Id);
          }
        }
        fileList.addAll(
          FileService.getInstance()
            .fetchContentVersionByEntityIds(reletedEntityIdList, false)
        );
      }
      if (!CollectionUtils.isListEmpty(fileList)) {
        return ApexResponse.OK(fileList);
      } else {
        return ApexResponse.fail(fileList);
      }
    } catch (CustomException ex) {
      log?.error(ex);
      return ApexResponse.exception(ex);
    } catch (Exception ex) {
      log?.error(ex);
      return ApexResponse.fail(ex);
    } finally {
      Logger.persist();
    }
  }
}