force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerInterest__c/CustomerInterest__c.object-meta.xml
<CustomObject>
    <description>Object store store cross sell product details selected by customers.</description>
    <label>Customer Interest</label>
    <nameField>
        <label>Customer Interest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerInterest__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Application</description>
    <label>Application</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Interests</relationshipLabel>
    <relationshipName>Customer_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerInterest__c/fields/InterestProduct__c.field-meta.xml
<CustomField>
    <fullName>InterestProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Interested product of customer</description>
    <label>Interest Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Customer Interests</relationshipLabel>
    <relationshipName>CustomerInterests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/FinancialAccount__c.object-meta.xml
<CustomObject>
    <description
  >A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Financial Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DAT-200</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>related product</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccountService__c/FinancialAccountService__c.object-meta.xml
<CustomObject>
    <description>Services opted by customer for Financial Account</description>
    <label>Financial Account Service</label>
    <nameField>
        <displayFormat>FAS-{0000}</displayFormat>
        <label>Financial Account Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccountService__c/fields/FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Services for Financial Account</description>
    <label>Financial Account</label>
    <referenceTo>FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Services</relationshipLabel>
    <relationshipName>FinancialAccountServices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialProduct__c/FinancialProduct__c.object-meta.xml
<CustomObject>
    <description>Object to store all product related data</description>
    <label>Financial Product</label>
    <nameField>
        <label>FinancialProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductFeature__c/ProductFeature__c.object-meta.xml
<CustomObject>
    <description>Product Feature to describe additional product</description>
    <label>Product Feature</label>
    <nameField>
        <label>Product Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductFeature__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to Financial Product</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Product Features</relationshipLabel>
    <relationshipName>ProductFeatures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductFeature__c/fields/ProductService__c.field-meta.xml
<CustomField>
    <fullName>ProductService__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to Product service</description>
    <label>Product Service</label>
    <referenceTo>ProductService__c</referenceTo>
    <relationshipLabel>Product Features</relationshipLabel>
    <relationshipName>ProductFeatures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductService__c/ProductService__c.object-meta.xml
<CustomObject>
    <description>Available Product services for products</description>
    <label>Product Service</label>
    <nameField>
        <label>Product Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductService__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to product object</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Product Services</relationshipLabel>
    <relationshipName>ProductServices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReferralProduct__c/ReferralProduct__c.object-meta.xml
<CustomObject>
    <description>Object to store Referral product details</description>
    <label>Referral Product</label>
    <nameField>
        <label>Referral Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReferralProduct__c/fields/CrossSellProduct__c.field-meta.xml
<CustomField>
    <fullName>CrossSellProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CrossSellProduct related to the product</description>
    <label>CrossSell Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Referral Products</relationshipLabel>
    <relationshipName>ReferralProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReferralProduct__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FinancialProduct</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Financial Products</relationshipLabel>
    <relationshipName>FinancialProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductServiceRepository.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Repository
 * @author Digital Align Team
 * @reference
 * @description
 **/
public with sharing class ProductServiceRepository extends DatabaseUtils {
  /**
   * @description Read Existing Service
   * @author Digital Align Team | 02-25-2022
   * @param Id financialAccountId
   * @return List<FinancialAccountService__c>
   */
  public static List<FinancialAccountService__c> readExistingService(Id financialAccountId) {
    Query query = Query.newInstance(FinancialAccountService__c.SObjectType)
      .addFields()
      .whereEq('FinancialAccount__c', financialAccountId)
      .orderBy('mflow__Order__c');
    return (List<FinancialAccountService__c>) getRecords(query.toString(true));
  }
  /**
   * @description Read Application with child record
   * Applicants contains only ids
   * Financial Application__c contains only Ids
   * @author Digital Align Team | 10-26-2021
   * @param Id applicationId
   * @return Application__c
   **/
  public static Application__c readApplicationWithFA(Id applicationId) {
    Query qry = Query.newInstance(Application__c.SObjectType)
      .addFields()
      .queryChild('mflow__FinancialAccounts__r')
      .addFields()
      .run()
      .addLimit(1)
      .whereEq('Id', applicationId);
    return (Application__c) getRecord(qry.toString());
  }
  /**
   * @description fetch templates based on filters
   * @author Digital Align Team | 01-04-2022
   * @param String productId
   * @return List<ProductService__c>
   **/
  public static List<ProductService__c> fetchServicesByProduct(string productId) {
    return (List<ProductService__c>) getRecords(
      Query.newInstance(ProductService__c.SObjectType)
        .addFields()
        .whereEq('mflow__IsActive__c', true)
        .andCon()
        .whereEq('FinancialProduct__c', productId)
        .toString()
    );
  }

  /**
   * @description Read Application For Referral
   * @author Digital Align Team | 04-08-2022
   * @param Id applicationId
   * @return Application__c
   **/
  public static Application__c readApplicationForReferral(Id applicationId) {
    Query qry = Query.newInstance(Application__c.SObjectType)
      .addFields()
      .queryChild('mflow__CustomerInterests__r')
      .addFields()
      .queryLookup('mflow__InterestProduct__r')
      .addFields()
      .run()
      .run()
      .queryChild('mflow__FinancialAccounts__r')
      .addFields()
      .run()
      .addLimit(1)
      .whereEq('Id', applicationId);
    return (Application__c) getRecord(qry.toString());
  }

  /**
   * @description  Fetch Referral Products
   * @author Digital Align Team | 04-08-2022
   * @param Set<Id> productIds
   * @return List<ReferralProduct__c>
   **/
  public static List<ReferralProduct__c> fetchReferralProducts(Set<Id> productIds) {
    return (List<ReferralProduct__c>) getRecords(
      Query.newInstance(ReferralProduct__c.SObjectType)
        .addFields()
        .queryLookup('mflow__CrossSellProduct__r')
        .addFields()
        .run()
        .whereEq('mflow__IsActive__c', true)
        .andCon()
        .whereIn('FinancialProduct__c', productIds)
        .andCon()
        .whereNotIn('CrossSellProduct__c', productIds)
        .orderBy('mflow__Order__c')
        .toString()
    );
  }

  /**
   * @description fetch all products
   * @author Digital Align Team | 03-22-2022
   * @return List<financialProduct__c>
   **/
  public static List<financialProduct__c> fetchProducts() {
    return (List<financialProduct__c>) DatabaseUtils.getRecords(
      Query.newInstance(financialProduct__c.SObjectType)
        .addFields()
        .queryChild('mflow__ProductFeatures__r')
        .addFields()
        .whereEq('mflow__ProductService__c', null)
        .andCon()
        .whereEq('mflow__Type__c', ApplicationConstant.PRODUCT_FEATURE_TYPE_PRODUCT_CONFIG)
        .orderBy('mflow__Order__c')
        .run()
        .whereEq('mflow__IsActive__c', true)
        .orderBy('mflow__Order__c')
        .toString()
    );
  }

  /**
   * @description fetch product features based on product Id
   * @author Digital Align Team | 03-25-2022
   * @param String productId
   * @return List<financialProduct__c>
   **/
  public static List<financialProduct__c> fetchProductWithFeatures(Id applicationId) {
    return (List<financialProduct__c>) getRecords(
      Query.newInstance(financialProduct__c.SObjectType)
        .addFields()
        .queryChild('mflow__ProductFeatures__r')
        .addFields()
        .whereEq('mflow__ProductService__c', null)
        .andCon()
        .whereEq('mflow__Type__c', ApplicationConstant.PRODUCT_FEATURE_TYPE_PRODUCT_DESC)
        .orderBy('mflow__Order__c')
        .run()
        .whereEq('mflow__IsActive__c', true)
        .andCon()
        .whereIn(
          'Id',
          Query.newInstance(mflow__FinancialAccount__c.SObjectType)
            .addFields('mflow__FinancialProduct__c')
            .whereEq('mflow__Application__c', applicationId)
            .toString()
        )
        .toString()
    );
  }
}