force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Application submission status by applicant</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Abandoned</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Review In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Submit for Review</fullName>
    </customValue>
    <customValue>
        <fullName>Saved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Funding in Progress</fullName>
    </customValue>
    <description>Status of application and applicants</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchToDeleteApplication.cls
/**
 * Copyright (c) 2022 Digital Align
 * @group BatchJob
 * @author Digital Align Team
 * @reference
 * @description  Delete Application from system
 * Make Sure Batch job Size is 5
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global class BatchToDeleteApplication implements Database.Batchable<sObject>, Database.Stateful {
  private Logger log = Logger.getInstance(BatchToDeleteApplication.class);
  /**
   * @description
   * @author Digital Align Team | 04-26-2022
   * @param Database.BatchableContext bc
   * @return Database.QueryLocator
   **/
  global Database.QueryLocator start(Database.BatchableContext bc) {
    log?.debug('Start BatchToDeleteApplication ');
    String qry = Query.newInstance(Application__c.SObjectType)
      .grpOpen()
      .whereEq('Status__c', ApplicationConstant.ABANDONED)
      .orCon()
      .whereEq('Status__c', ApplicationConstant.SAVED)
      .orCon()
      .whereEq('Status__c', ApplicationConstant.CANCELLED)
      .grpClose()
      .andCon()
      .whereLte('LastModifiedDate', DateTime.now().addDays(-10))
      .addLimit(1000)
      .toString();
    log?.debug('qry :' + qry);
    return Database.getQueryLocator(qry);
  }

  /**
   * @description
   * @author Digital Align Team | 04-26-2022
   * @param Database.BatchableContext BC
   * @param List<Application__c> scope
   **/
  global void execute(Database.BatchableContext bc, List<Application__c> applications) {
    log?.debug('execute BatchToDeleteApplication ');
    for (Application__c application : applications) {
      ApplicationPersistService.getInstance().deleteEntity(application.Id);
    }
    Logger.persist();
  }

  /**
   * @description
   * @author Digital Align Team | 04-26-2022
   * @param Database.BatchableContext BC
   **/
  global void finish(Database.BatchableContext bc) {
    log?.debug('Finished BatchToDeleteApplication ');
    Logger.persist();
  }
}