force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerInterest__c/CustomerInterest__c.object-meta.xml
<CustomObject>
    <description>Object store store cross sell product details selected by customers.</description>
    <label>Customer Interest</label>
    <nameField>
        <label>Customer Interest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerInterest__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Application</description>
    <label>Application</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Interests</relationshipLabel>
    <relationshipName>Customer_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerInterest__c/fields/ImageName__c.field-meta.xml
<CustomField>
    <fullName>ImageName__c</fullName>
    <description>Product image name</description>
    <label>Image Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerInterest__c/fields/ImageURL__c.field-meta.xml
<CustomField>
    <fullName>ImageURL__c</fullName>
    <description>product Image URL</description>
    <label>Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CustomerInterest__c/fields/InterestProduct__c.field-meta.xml
<CustomField>
    <fullName>InterestProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Interested product of customer</description>
    <label>Interest Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Customer Interests</relationshipLabel>
    <relationshipName>CustomerInterests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerInterest__c/fields/IsSelected__c.field-meta.xml
<CustomField>
    <fullName>IsSelected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if service is selected by customer</description>
    <label>isSelected?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/FinancialAccount__c.object-meta.xml
<CustomObject>
    <description
  >A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Financial Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DAT-200</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>related product</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccountService__c/FinancialAccountService__c.object-meta.xml
<CustomObject>
    <description>Services opted by customer for Financial Account</description>
    <label>Financial Account Service</label>
    <nameField>
        <displayFormat>FAS-{0000}</displayFormat>
        <label>Financial Account Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccountService__c/fields/FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Services for Financial Account</description>
    <label>Financial Account</label>
    <referenceTo>FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Services</relationshipLabel>
    <relationshipName>FinancialAccountServices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccountService__c/fields/isSelected__c.field-meta.xml
<CustomField>
    <fullName>isSelected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if service is selected by customer</description>
    <label>isSelected?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinancialAccountService__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Sorting order</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FinancialProduct__c/FinancialProduct__c.object-meta.xml
<CustomObject>
    <description>Object to store all product related data</description>
    <label>Financial Product</label>
    <nameField>
        <label>FinancialProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialProduct__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Product end date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FinancialProduct__c/fields/LongDescription__c.field-meta.xml
<CustomField>
    <fullName>LongDescription__c</fullName>
    <description>Product long description</description>
    <label>Long Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FinancialProduct__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Order which wil be used to display the order in which products will be displayed.</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductService__c/ProductService__c.object-meta.xml
<CustomObject>
    <description>Available Product services for products</description>
    <label>Product Service</label>
    <nameField>
        <label>Product Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductService__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of additional service</description>
    <label>Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductService__c/fields/Design__c.field-meta.xml
<CustomField>
    <fullName>Design__c</fullName>
    <description>Any specific design to be shown in UI</description>
    <label>Design</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductService__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to product object</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Product Services</relationshipLabel>
    <relationshipName>ProductServices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductService__c/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <description>Name of service offered</description>
    <label>Service Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductService__c/fields/showQuestions__c.field-meta.xml
<CustomField>
    <fullName>showQuestions__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >True if any questions are associated with the service</description>
    <label>showQuestions?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ReferralProduct__c/ReferralProduct__c.object-meta.xml
<CustomObject>
    <description>Object to store Referral product details</description>
    <label>Referral Product</label>
    <nameField>
        <label>Referral Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReferralProduct__c/fields/CrossSellProduct__c.field-meta.xml
<CustomField>
    <fullName>CrossSellProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CrossSellProduct related to the product</description>
    <label>CrossSell Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Referral Products</relationshipLabel>
    <relationshipName>ReferralProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReferralProduct__c/fields/ExternalCode__c.field-meta.xml
<CustomField>
    <fullName>ExternalCode__c</fullName>
    <description>To store product code from financial institute</description>
    <label>External Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReferralProduct__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FinancialProduct</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Financial Products</relationshipLabel>
    <relationshipName>FinancialProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReferralProduct__c/fields/IsSelected__c.field-meta.xml
<CustomField>
    <fullName>IsSelected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if service is selected by customer</description>
    <label>IsSelected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ReferralProduct__c/fields/LongDescription__c.field-meta.xml
<CustomField>
    <fullName>LongDescription__c</fullName>
    <description>Product long description</description>
    <label>Long Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReferralProduct__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Product start date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ProductServiceResolver.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Resolver
 * @author Digital Align Team
 * @reference
 * @description
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global with sharing class ProductServiceResolver extends AbstractService {
  @TestVisible
  private static ProductServiceResolver serviceInstance;

  public ProductServiceResolver() {
    super(ProductServiceResolver.class);
  }

  /**
   * @description Provides a singleton instance of ProductServiceResolver from which all other class methods can be accessed.
   * @author Digital Align Team | 07-22-2021
   * @return Object  singleton
   **/
  public static ProductServiceResolver getInstance() {
    if (serviceInstance == null) {
      serviceInstance = (ProductServiceResolver) getInstance(ProductServiceResolver.class);
    }
    return serviceInstance;
  }

  /**
   * @description
   * @author Digital Align Team | 01-05-2022
   * @param String data
   * @return List<FinancialAccountService__c>
   **/
  global virtual List<FinancialAccountService__c> fetchServices(String data) {
    Application__c application = ProductServiceRepository.readApplicationWithFA(ApexRequest.getApplicationId());
    log?.debug('application=' + application);

    List<FinancialAccountService__c> financialAccountService = new List<FinancialAccountService__c>();

    for (FinancialAccount__c financialAccount : application.FinancialAccounts__r) {
      financialAccountService.addAll(ProductServiceRepository.readExistingService(financialAccount.Id));
    }

    if (!financialAccountService.isEmpty()) {
      return financialAccountService;
    }

    for (FinancialAccount__c financialAccount : application.FinancialAccounts__r) {
      List<ProductService__c> services = ProductServiceRepository.fetchServicesByProduct(
        financialAccount.FinancialProduct__r.Id
      );
      log?.debug(services);

      financialAccountService.addAll(this.buildService(services, financialAccount.Id));
    }
    ProductServiceRepository.upsertRecords(financialAccountService);
    return financialAccountService;
  }
  /**
   * @description  build survey object based on the template list
   * @author Digital Align Team | 01-05-2022
   * @param List<ProductService__c> productServices
   * @param Id financialAccountId
   * @return  List<FinancialAccountService__c>
   **/
  global virtual List<FinancialAccountService__c> buildService(
    List<ProductService__c> productServices,
    Id financialAccountId
  ) {
    List<FinancialAccountService__c> serviceList = new List<FinancialAccountService__c>();
    for (ProductService__c productService : productServices) {
      FinancialAccountService__c finProductServiceObj = new FinancialAccountService__c();

      if (String.isNotBlank(financialAccountId)) {
        finProductServiceObj.FinancialAccount__c = financialAccountId;
      }
      finProductServiceObj.Order__c = productService.Order__c;
      finProductServiceObj.Required__c = productService.Required__c;
      finProductServiceObj.Description__c = productService.Description__c;
      finProductServiceObj.Design__c = productService.Design__c;
      finProductServiceObj.Required__c = productService.Required__c;
      finProductServiceObj.ServiceName__c = productService.ServiceName__c;
      finProductServiceObj.ShowQuestions__c = productService.ShowQuestions__c;
      finProductServiceObj.isSelected__c = false;
      serviceList.add(finProductServiceObj);
    }
    return serviceList;
  }
  /**
   * @description fetch referral Product product for the product selected in the application
   * @author Digital Align Team | 04-03-2022
   * @param String data
   * @return List<CustomerInterest__c>
   **/
  global virtual List<CustomerInterest__c> fetchReferralProducts(String data) {
    mflow__Application__c application = ProductServiceRepository.readApplicationWithFA(ApexRequest.getApplicationId());

    List<CustomerInterest__c> customerInterests = new List<CustomerInterest__c>();

    for (FinancialAccount__c financialAccount : application.FinancialAccounts__r) {
      List<ReferralProduct__c> ReferralProducts = ProductServiceRepository.fetchReferralProductByProduct(
        financialAccount.FinancialProduct__r.Id
      );
      customerInterests.addAll(this.buildReferralProduct(ReferralProducts, application.Id));
    }
    ProductServiceRepository.upsertRecords(customerInterests);
    return customerInterests;
  }
  /**
   * @description  build referral Products based on the interest list
   * @author Digital Align Team | 04-03-2022
   * @param List<ReferralProduct__c> ReferralProducts
   * @param Id applicationId
   * @return  List<CustomerInterest__c>
   **/
  global virtual List<CustomerInterest__c> buildReferralProduct(
    List<ReferralProduct__c> ReferralProducts,
    Id applicationId
  ) {
    List<CustomerInterest__c> customerInterests = new List<CustomerInterest__c>();
    for (ReferralProduct__c referralProduct : ReferralProducts) {
      CustomerInterest__c customerInterestObj = new CustomerInterest__c();

      if (String.isNotBlank(applicationId)) {
        customerInterestObj.Application__c = applicationId;
      }
      customerInterestObj.Name = referralProduct.Name;
      customerInterestObj.EndDate__c = referralProduct.EndDate__c;
      customerInterestObj.ExternalCode__c = referralProduct.ExternalCode__c;
      customerInterestObj.ImageName__c = referralProduct.ImageName__c;
      customerInterestObj.ImageURL__c = referralProduct.ImageURL__c;
      customerInterestObj.InternalCode__c = referralProduct.InternalCode__c;
      customerInterestObj.InterestProduct__c = referralProduct.CrossSellProduct__c;
      customerInterestObj.LongDescription__c = referralProduct.LongDescription__c;
      customerInterestObj.Order__c = referralProduct.Order__c;
      customerInterestObj.StartDate__c = referralProduct.StartDate__c;
      customerInterestObj.Required__c = referralProduct.Required__c;
      customerInterestObj.isSelected__c = false;
      customerInterests.add(customerInterestObj);
    }
    return customerInterests;
  }
}