force-app/main/default/objects/Account/fields/BranchCode__c.field-meta.xml
<CustomField>
    <fullName>BranchCode__c</fullName>
    <description>Branch Code</description>
    <label>Branch Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FlowState__c.field-meta.xml
<CustomField>
    <fullName>FlowState__c</fullName>
    <description>Page name where the flow is stopped.</description>
    <inlineHelpText>Page name where the flow is stopped.</inlineHelpText>
    <label>Flow State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Get-Started</fullName>
            </value>
            <value>
                <fullName>Eligibility-Confirmation</fullName>
            </value>
            <value>
                <fullName>Family-Connect</fullName>
            </value>
            <value>
                <fullName>Personal-Information</fullName>
            </value>
            <value>
                <fullName>Otp-Verification</fullName>
            </value>
            <value>
                <fullName>Address-Verification</fullName>
            </value>
            <value>
                <fullName>Joint</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Emergency-Contact</fullName>
            </value>
            <value>
                <fullName>Employment-Information</fullName>
            </value>
            <value>
                <fullName>Review-Information</fullName>
            </value>
            <value>
                <fullName>Password</fullName>
            </value>
            <value>
                <fullName>Email-Confirmation</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Disclosures</fullName>
            </value>
            <value>
                <fullName>Final-Confirmation</fullName>
            </value>
            <value>
                <fullName>Welcome-Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application for grorup MintFlow related details</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/FlowState__c.field-meta.xml
<CustomField>
    <fullName>FlowState__c</fullName>
    <description>Page name where the flow is stopped.</description>
    <inlineHelpText>Page name where the flow is stopped.</inlineHelpText>
    <label>Flow State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FlowState</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/FlowType__c.field-meta.xml
<CustomField>
    <fullName>FlowType__c</fullName>
    <description>Flow Type where application is reached</description>
    <inlineHelpText>Flow Type where application is reached</inlineHelpText>
    <label>Flow Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FlowType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SessionExpireTime__c.field-meta.xml
<CustomField>
    <fullName>SessionExpireTime__c</fullName>
    <description>Session Expire Time</description>
    <inlineHelpText>OTP expire time</inlineHelpText>
    <label>Session Expire Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Applicant__c/recordTypes/Joint.recordType-meta.xml
<RecordType>
    <fullName>Joint</fullName>
    <active>true</active>
    <description>Joint Applicant</description>
    <label>Joint</label>
</RecordType>

force-app/main/default/objects/Applicant__c/recordTypes/Primary.recordType-meta.xml
<RecordType>
    <fullName>Primary</fullName>
    <active>true</active>
    <description>Primary Applicant</description>
    <label>Primary</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/BranchCode__c.field-meta.xml
<CustomField>
    <fullName>BranchCode__c</fullName>
    <description>Branch Code</description>
    <label>Branch Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/BranchName__c.field-meta.xml
<CustomField>
    <fullName>BranchName__c</fullName>
    <label>Branch Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/FlowState__c.field-meta.xml
<CustomField>
    <fullName>FlowState__c</fullName>
    <description>Page name where the flow is stopped.</description>
    <inlineHelpText>Page name where the flow is stopped.</inlineHelpText>
    <label>Flow State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FlowState</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/FlowType__c.field-meta.xml
<CustomField>
    <fullName>FlowType__c</fullName>
    <description>Flow Type where application is reached</description>
    <inlineHelpText>Flow Type where application is reached</inlineHelpText>
    <label>Flow Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FlowType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/ParentApplication__c.field-meta.xml
<CustomField>
    <fullName>ParentApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connected Application</description>
    <label>Parent Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Child Applications</relationshipLabel>
    <relationshipName>ChildApplications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApplicationConfiguration__c/ApplicationConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Configuration</label>
</CustomObject>

force-app/main/default/objects/ApplicationConfiguration__c/fields/SessionExpirationTime__c.field-meta.xml
<CustomField>
    <fullName>SessionExpirationTime__c</fullName>
    <description>Session Expiration Time in Mintues</description>
    <label>Session Expiration Time in Mintues</label>
    <required>true</required>
    <type>Number</type>
    <scale>0</scale>
    <precision>4</precision>
</CustomField>

force-app/main/default/objects/ContactPointAddress/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and contact point address</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Contact Point Addresses</relationshipLabel>
    <relationshipName>ContactPointAddresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employment__c/Employment__c.object-meta.xml
<CustomObject>
    <description
  >Represents information about a person&apos;s employment history.</description>
    <label>Employment</label>
    <nameField>
        <displayFormat>Emp-{00000}</displayFormat>
        <label>Employment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Employment type</description>
    <label>Employment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Previous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/FinancialAccount__c.object-meta.xml
<CustomObject>
    <description
  >A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Financial Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DAT-200</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>related product</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialProduct__c/FinancialProduct__c.object-meta.xml
<CustomObject>
    <description>Object to store all product related data</description>
    <label>Financial Product</label>
    <nameField>
        <label>FinancialProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialProduct__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Lending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__Employment__c/FinServ__Employment__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__EmploymentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about a person&apos;s employment history.</description>
    <label>Employment</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and Employment realtionship</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Employment</relationshipLabel>
    <relationshipName>Employments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__Employment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>employment verification type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fsc-app/main/default/objects/FinServ__IdentificationDocument__c/FinServ__IdentificationDocument__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__IdentificationDocumentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about documents used to verify a person&apos;s identity.</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>DOC-{000000000}</displayFormat>
        <label>Document</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IdentificationDocument__c/IdentificationDocument__c.object-meta.xml
<CustomObject>
    <description>Identification Document for Applicants</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LeadConfiguration__c/LeadConfiguration__c.object-meta.xml
<CustomObject>
    <description
  >Object for string the configuration setting for calculating the lead scores of the application</description>
    <label>Lead Configuration</label>
    <nameField>
        <label>Lead Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LeadConfiguration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Field to store the type of lead configuration like eligibility, state names etc</description>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/FlowState.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GetStarted</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility</fullName>
    </customValue>
    <customValue>
        <fullName>CountyValidate</fullName>
    </customValue>
    <customValue>
        <fullName>InvalidCounty</fullName>
    </customValue>
    <customValue>
        <fullName>FamilyConnect</fullName>
    </customValue>
    <customValue>
        <fullName>PersonalInfo</fullName>
    </customValue>
    <customValue>
        <fullName>OtpVerification</fullName>
    </customValue>
    <customValue>
        <fullName>IdentityVerification</fullName>
    </customValue>
    <customValue>
        <fullName>DocumentUpload</fullName>
    </customValue>
    <customValue>
        <fullName>AddressVerification</fullName>
    </customValue>
    <customValue>
        <fullName>AdditionalApplicant</fullName>
    </customValue>
    <customValue>
        <fullName>EmploymentReview</fullName>
    </customValue>
    <customValue>
        <fullName>EmployeeInfo</fullName>
    </customValue>
    <customValue>
        <fullName>Review</fullName>
    </customValue>
    <customValue>
        <fullName>Questionary</fullName>
    </customValue>
    <customValue>
        <fullName>Disclosure</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Sorry</fullName>
    </customValue>
    <customValue>
        <fullName>WelcomeJoint</fullName>
    </customValue>
    <customValue>
        <fullName>Funding</fullName>
    </customValue>
    <customValue>
        <fullName>Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>BranchPassword</fullName>
    </customValue>
    <customValue>
        <fullName>Congratulation</fullName>
    </customValue>
    <customValue>
        <fullName>EmailConfirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Agreements</fullName>
    </customValue>
    <customValue>
        <fullName>oow</fullName>
    </customValue>
    <customValue>
        <fullName>DemographicInfo</fullName>
    </customValue>
    <customValue>
        <fullName>AssetAndLiability</fullName>
    </customValue>
    <customValue>
        <fullName>Property</fullName>
    </customValue>
    <description>UI Flow State Indicator</description>
    <masterLabel>FlowState</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FlowType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ApplicationFlow</fullName>
    </customValue>
    <customValue>
        <fullName>JointFlow</fullName>
    </customValue>
    <customValue>
        <fullName>FundingFlow</fullName>
    </customValue>
    <description>UI Flow Type Indicator</description>
    <masterLabel>FlowType</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ApplicationServiceHelper.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Helper
 * @author Digital Align Team
 * @reference
 * @description
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global virtual with sharing class ApplicationServiceHelper extends AbstractService {
  @TestVisible
  private static ApplicationServiceHelper serviceInstance;

  public ApplicationServiceHelper() {
    super(ApplicationServiceHelper.class);
  }

  /**
   * @description Provides a singleton instance of ApplicationServiceHelper from which all other class methods can be accessed.
   * @author Digital Align Team | 07-27-2021
   * @return Object  singleton
   **/
  public static ApplicationServiceHelper getInstance() {
    if (serviceInstance == null) {
      serviceInstance = (ApplicationServiceHelper) getInstance(ApplicationServiceHelper.class);
    }
    return serviceInstance;
  }

  /**
   * @description get current ipaddress
   * @author Digital Align Team | 10-11-2021
   * @return String
   **/
  global virtual String getIpAddress() {
    String ipAddress;
    //System.auth.SessionManagement.getCurrentSession().get('SourceIp');

    if (ApexPages.currentPage() != null && String.isBlank(ipAddress)) {
      ipAddress = ApexPages.currentPage().getHeaders().get('True-Client-IP');
      // X-Salesforce-SIP has the value when no caching integration or via secure URL.
      if (String.isBlank(ipAddress)) {
        ipAddress = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
      }
      // get IP address when no caching (sandbox, dev, secure urls)
      if (String.isBlank(ipAddress)) {
        ipAddress = ApexPages.currentPage().getHeaders().get('X-Forwarded-For');
      }
    }
    log?.info('getIpAddress -> IP address -> ' + ipAddress);
    return ipAddress;
  }

  /**
   * @description resolve branch location
   * @author Digital Align Team | 12-03-2021
   * @param Application__c application
   * @return Application__c
   **/
  global virtual Application__c resolveBranchLocation(Application__c application) {
    //#pending Create a Branch Object to connect application
    application.BranchCode__c = '0001';
    application.BranchName__c = 'Main Branch';
    return application;
  }

  /**
   * @description update application flow state
   * @author Digital Align Team | 01-13-2022
   * @param Application__c application
   * @param Applicant__c applicant
   * @return Application__c
   **/
  global virtual Application__c updateFlowState(Application__c application, List<Applicant__c> applicants) {
    if (ApexRequest.getApplicantType() == 'Primary') {
      for (Applicant__c applicant : applicants) {
        if (applicant.mflow__ApplicantType__c == ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE) {
          applicant.FlowState__c = ApexRequest.getRequest().currentPage;
          applicant.FlowType__c = ApexRequest.getFlowType();
          applicant.sessionExpireTime__c = Datetime.now()
            .addMinutes((Integer) ApplicationConfiguration__c.getOrgDefaults().SessionExpirationTime__c);
          ApplicationRepository.UpsertRecord(applicant);
          break;
        }
      }
      application.FlowState__c = ApexRequest.getRequest().currentPage;
      application.FlowType__c = ApexRequest.getFlowType();
      ApplicationRepository.UpsertRecord(application);
    } else if (ApexRequest.getApplicantType() == 'Joint') {
      for (Applicant__c applicant : applicants) {
        if (applicant.Id == ApexRequest.getApplicantId()) {
          applicant.FlowState__c = ApexRequest.getRequest().currentPage;
          applicant.FlowType__c = ApexRequest.getFlowType();
          applicant.sessionExpireTime__c = Datetime.now()
            .addMinutes((Integer) ApplicationConfiguration__c.getOrgDefaults().SessionExpirationTime__c);
          ApplicationRepository.UpsertRecord(applicant);
          break;
        }
      }
    }
    return application;
  }

  /**
   * @description Clone Application into new Application
   * @author Digital Align Team | 03-18-2022
   * @param Map<String Object> params
   * @return Application__c
   **/
  global virtual Application__c cloneApplicationRecord(Map<String, Object> params) {
    String applicationName = (String) params.get('app');
    String internalProductCode = (string) params.get('pid');
    String ch = (string) params.get('ch');

    Application__c oldApplication = ApplicationRepository.readApplicationToClone(applicationName);
    List<Applicant__c> oldApplicants = ApplicationRepository.readApplicantsToClone(oldApplication.Id);
    FinancialProduct__c selectedProduct = FinancialAccountRepository.readFinancialProductByInternalCode(
      internalProductCode
    );

    if (oldApplication == null || selectedProduct == null) {
      throw new CustomException('Something went wrong! Check application number and product');
    }

    //Application
    Application__c newApplication = oldApplication.clone(false, true, false, false);
    newApplication.ParentApplication__c = oldApplication.Id;
    newApplication.Status__c = ApplicationConstant.IN_PROGRESS;
    newApplication.CreatedChannel__c = oldApplication.LastUsedChannel__c = ch;
    newApplication.ApplicationType__c = selectedProduct.Type__c;
    newApplication.IsExistingCustomer__c = true;
    newApplication.FlowState__c = 'Review';
    newApplication.FlowType__c = 'ApplicationFlow';
    newApplication.Source__c = 'Additional Product';
    newApplication.Version__c = ApplicationConfiguration__c.getInstance().PackageVersion__c;
    newApplication.IPAddress__c = ApplicationServiceHelper.getInstance().getIpAddress();
    newApplication = this.resolveBranchLocation(newApplication);
    ApplicationRepository.upsertRecord(newApplication);

    ApexRequest.setApplicationId(newApplication.Id);
    //Financial Account
    FinancialAccount__c financialAccount = new FinancialAccount__c();
    financialAccount.FinancialProduct__c = selectedProduct.Id;
    financialAccount.Ownership__c = oldApplicants.size() > 1 ? 'Joint' : 'Individual';
    financialAccount.Status__c = ApplicationConstant.IN_PROGRESS;
    financialAccount.Stage__c = 'Active';
    financialAccount.isPrimary__c = true;
    financialAccount.Application__c = newApplication.Id;
    financialAccount.RecordTypeId = SObjectUtils.recordTypeIdByName(
      FinancialAccount__c.SObjectType,
      selectedProduct.Category__c
    );
    FinancialAccountRepository.upsertRecord(financialAccount);

    //Applicants
    List<Applicant__c> newApplicants = new List<Applicant__c>();
    Applicant__c newPrimaryApplicant;
    for (Applicant__c oldApplicant : oldApplicants) {
      Applicant__c newApplicant = oldApplicant.clone(false, true, false, false);
      newApplicant.Application__c = newApplication.Id;
      newApplicant.FlowState__c = '';
      newApplicant.FlowType__c = 'ApplicationFlow';
      newApplicant.Status__c = ApplicationConstant.IN_PROGRESS;
      //Primary Applicant
      if (oldApplicant.RecordType.Name == ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE) {
        newPrimaryApplicant = newApplicant;
        newApplicant.IsExistingCustomer__c = true;
      }
      newApplicants.add(newApplicant);
    }
    ApplicationRepository.upsertRecords(newApplicants);
    ApexRequest.setApplicantId(newPrimaryApplicant.Id);
    //Applicant Child

    List<IdentificationDocument__c> newIdentityDocs = new List<IdentificationDocument__c>();
    List<Employment__c> newEmployments = new List<Employment__c>();
    List<ContactPointAddress> newAddreses = new List<ContactPointAddress>();
    for (Applicant__c newApplicant : newApplicants) {
      //Identification Document
      for (IdentificationDocument__c oldIdentityDoc : newApplicant.IdentificationDocuments__r) {
        IdentificationDocument__c newIdentityDoc = oldIdentityDoc.clone(false, true, false, false);
        newIdentityDoc.Applicant__c = newApplicant.Id;
        newIdentityDocs.add(newIdentityDoc);
      }
      //Employment
      for (Employment__c oldEmployment : newApplicant.Employments__r) {
        Employment__c newEmployment = oldEmployment.clone(false, true, false, false);
        newEmployment.Applicant__c = newApplicant.Id;
        newEmployments.add(newEmployment);
      }
      // //Contact Point Address
      for (ContactPointAddress oldAddress : newApplicant.ContactPointAddresses__r) {
        ContactPointAddress newAddress = oldAddress.clone(false, true, false, false);
        newAddress.Applicant__c = newApplicant.Id;
        newAddreses.add(newAddress);
      }
    }
    ApplicationRepository.upsertRecords(newIdentityDocs);
    ApplicationRepository.upsertRecords(newEmployments);
    ApplicationRepository.upsertRecords(newAddreses);

    return newApplication;
  }

  public Map<String, Object> calculateLeadScore(Application__c application) {
    Map<String, Object> mapData = new Map<String, Object>();
    Map<String, String> mapFilter = new Map<String, String>();
    String productId;

    List<financialProduct__c> products = ProductServiceRepository.fetchProductWithFeatures(application.Id);
    try {
      if (products != null && products.size() > 0) {
        //Calcuate Lead Score based on product and State weightage;
        mapFilter.put('Type', 'State');
        mapFilter.put('Category', products[0].Category__c);
        mapFilter.put('Value', application.mflow__FlowState__c);
        mapData = calculateLeadBasedonState(mapfilter, mapData, products[0]);

        //Calculate the lead score based on eligibility
        mapFilter = new Map<String, String>();
        mapFilter.put('Type', 'Eligibility');
        mapFilter.put('Value', application.IsCountyEligible__c ? 'True' : 'False');
        mapData = calculateLeadBasedonEligibility(mapfilter, mapData);
        //Calculate the lead score based on KYC
        mapFilter = new Map<String, String>();
        mapFilter.put('Type', 'KYC');
        mapFilter.put('Value', application.mflow__KYCStatus__c == 'Passed' ? 'True' : 'False');
        System.debug('  mapData filter kyc::' + mapFilter);
        mapData = calculateLeadBasedonKYC(mapfilter, mapData);

        System.debug('  mapData Final::' + mapData);
      }
    } catch (exception ex) {
      system.debug(' exception at : ' + ex.getLineNumber() + ex.getMessage());
    }

    return null;
  }

  public Map<String, Object> calculateLeadBasedonState(
    Map<String, String> mapFilter,
    Map<String, Object> mapData,
    financialProduct__c product
  ) {
    Decimal weightage;
    List<LeadConfiguration__c> leadConfigList = new List<LeadConfiguration__c>();
    leadConfigList = ApplicationRepository.fetchLeadConfiguration(mapFilter);
    if (leadConfigList != null && leadConfigList.size() > 0) {
      weightage = leadConfigList[0].Weightage__c * product.Weightage__c;
      mapData.put(
        'Product : ' +
        product.Name +
        ', Completion State  : ' +
        mapFilter.get('Value') +
        ', State Score  ',
        weightage
      );
    }
    return mapData;
  }

  public Map<String, Object> calculateLeadBasedonEligibility(
    Map<String, String> mapFilter,
    Map<String, Object> mapData
  ) {
    List<LeadConfiguration__c> leadConfigList = new List<LeadConfiguration__c>();
    leadConfigList = ApplicationRepository.fetchLeadConfiguration(mapFilter);
    if (leadConfigList.size() > 0) {
      mapData.put('Eligibility Score', (Object) (leadConfigList[0].Weightage__c));
    }
    return mapdata;
  }

  public Map<String, object> calculateLeadBasedonKYC(Map<String, String> mapFilter, Map<String, Object> mapData) {
    system.debug('leadConfigList::');
    List<LeadConfiguration__c> leadConfigList = new List<LeadConfiguration__c>();
    leadConfigList = ApplicationRepository.fetchLeadConfiguration(mapFilter);
    if (leadConfigList.size() > 0) {
      system.debug('leadConfigList::' + leadConfigList);
      mapData.put('KYC Score', (Object) (leadConfigList[0].Weightage__c));
    }
    return mapdata;
  }
}