force-app/main/default/objects/Account/fields/ExternalApplicationNumber__c.field-meta.xml
<CustomField>
    <fullName>ExternalApplicationNumber__c</fullName>
    <description>To save External Application Number</description>
    <label>LOS Application Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalApplicationStatus__c.field-meta.xml
<CustomField>
    <fullName>ExternalApplicationStatus__c</fullName>
    <description>To store External Application Status</description>
    <label>External Application Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__KYCStatus__c.field-meta.xml
<CustomField>
    <fullName>FinServ__KYCStatus__c</fullName>
    <label>KYC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed - Valid</fullName>
            </value>
            <value>
                <fullName>Completed - Invalid</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abandoned,</fullName>
            </value>
            <value>
                <fullName>Approved,</fullName>
            </value>
            <value>
                <fullName>Cancelled,</fullName>
            </value>
            <value>
                <fullName>Completed,</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Review,</fullName>
                <default>true</default>
                <label>Pending Review,</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Submitted,</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FlowState__c.field-meta.xml
<CustomField>
    <fullName>FlowState__c</fullName>
    <description>Page name where the flow is stopped.</description>
    <inlineHelpText>Page name where the flow is stopped.</inlineHelpText>
    <label>Flow State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Get-Started</fullName>
            </value>
            <value>
                <fullName>Eligibility-Confirmation</fullName>
            </value>
            <value>
                <fullName>Family-Connect</fullName>
            </value>
            <value>
                <fullName>Personal-Information</fullName>
            </value>
            <value>
                <fullName>Otp-Verification</fullName>
            </value>
            <value>
                <fullName>Address-Verification</fullName>
            </value>
            <value>
                <fullName>Joint</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Emergency-Contact</fullName>
            </value>
            <value>
                <fullName>Employment-Information</fullName>
            </value>
            <value>
                <fullName>Review-Information</fullName>
            </value>
            <value>
                <fullName>Password</fullName>
            </value>
            <value>
                <fullName>Email-Confirmation</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Disclosures</fullName>
            </value>
            <value>
                <fullName>Final-Confirmation</fullName>
            </value>
            <value>
                <fullName>Welcome-Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application for grorup MintFlow related details</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/CreditScore__c.field-meta.xml
<CustomField>
    <fullName>CreditScore__c</fullName>
    <description>To store Credit Score</description>
    <label>Credit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerNumber__c</fullName>
    <description>Customer number is he is an existing customer</description>
    <label>Customer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/CustomerScore__c.field-meta.xml
<CustomField>
    <fullName>CustomerScore__c</fullName>
    <description>To store Customer score result</description>
    <label>Customer Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/FlowState__c.field-meta.xml
<CustomField>
    <fullName>FlowState__c</fullName>
    <description>Page name where the flow is stopped.</description>
    <inlineHelpText>Page name where the flow is stopped.</inlineHelpText>
    <label>Flow State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FlowState</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/HighRiskConsumer__c.field-meta.xml
<CustomField>
    <fullName>HighRiskConsumer__c</fullName>
    <description>To store High Risk Consumer result</description>
    <label>High Risk Consumer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IdentityVerificationStatus__c.field-meta.xml
<CustomField>
    <fullName>IdentityVerificationStatus__c</fullName>
    <label>Identity Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Not Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/OFAC__c.field-meta.xml
<CustomField>
    <fullName>OFAC__c</fullName>
    <description>To store OFAC decision details</description>
    <label>OFAC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/OverallDebitBureauResult__c.field-meta.xml
<CustomField>
    <fullName>OverallDebitBureauResult__c</fullName>
    <description>to store Overall Debit Bureau Result</description>
    <label>Overall Debit Bureau Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/QualifiedDecision__c.field-meta.xml
<CustomField>
    <fullName>QualifiedDecision__c</fullName>
    <description>To store Qualifile result.</description>
    <label>Qualifile Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/QualifiedScore__c.field-meta.xml
<CustomField>
    <fullName>QualifiedScore__c</fullName>
    <description>To store Qualified score result</description>
    <label>Qualified Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/RunWithKIQ__c.field-meta.xml
<CustomField>
    <fullName>RunWithKIQ__c</fullName>
    <description>To store Run with KIQ result</description>
    <label>Run With KIQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/RunWithoutKIQ__c.field-meta.xml
<CustomField>
    <fullName>RunWithoutKIQ__c</fullName>
    <description>To store KIQ details.</description>
    <label>Run Without KIQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SSNValidation__c.field-meta.xml
<CustomField>
    <fullName>SSNValidation__c</fullName>
    <description>To store SSN Validation result</description>
    <label>SSN Validation</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Application submission status by applicant</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/recordTypes/Joint.recordType-meta.xml
<RecordType>
    <fullName>Joint</fullName>
    <active>true</active>
    <description>Joint Applicant</description>
    <label>Joint</label>
</RecordType>

force-app/main/default/objects/Applicant__c/recordTypes/Primary.recordType-meta.xml
<RecordType>
    <fullName>Primary</fullName>
    <active>true</active>
    <description>Primary Applicant</description>
    <label>Primary</label>
</RecordType>

force-app/main/default/globalValueSets/FlowState.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GetStarted</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility</fullName>
    </customValue>
    <customValue>
        <fullName>CountyValidate</fullName>
    </customValue>
    <customValue>
        <fullName>InvalidCounty</fullName>
    </customValue>
    <customValue>
        <fullName>FamilyConnect</fullName>
    </customValue>
    <customValue>
        <fullName>PersonalInfo</fullName>
    </customValue>
    <customValue>
        <fullName>OtpVerification</fullName>
    </customValue>
    <customValue>
        <fullName>IdentityVerification</fullName>
    </customValue>
    <customValue>
        <fullName>DocumentUpload</fullName>
    </customValue>
    <customValue>
        <fullName>AddressVerification</fullName>
    </customValue>
    <customValue>
        <fullName>AdditionalApplicant</fullName>
    </customValue>
    <customValue>
        <fullName>EmploymentReview</fullName>
    </customValue>
    <customValue>
        <fullName>EmployeeInfo</fullName>
    </customValue>
    <customValue>
        <fullName>Review</fullName>
    </customValue>
    <customValue>
        <fullName>Questionary</fullName>
    </customValue>
    <customValue>
        <fullName>Disclosure</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Sorry</fullName>
    </customValue>
    <customValue>
        <fullName>WelcomeJoint</fullName>
    </customValue>
    <customValue>
        <fullName>Funding</fullName>
    </customValue>
    <customValue>
        <fullName>Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>BranchPassword</fullName>
    </customValue>
    <customValue>
        <fullName>Congratulation</fullName>
    </customValue>
    <customValue>
        <fullName>EmailConfirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Agreements</fullName>
    </customValue>
    <customValue>
        <fullName>oow</fullName>
    </customValue>
    <customValue>
        <fullName>DemographicInfo</fullName>
    </customValue>
    <customValue>
        <fullName>AssetAndLiability</fullName>
    </customValue>
    <customValue>
        <fullName>Property</fullName>
    </customValue>
    <description>UI Flow State Indicator</description>
    <masterLabel>FlowState</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/KycReviewService.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Service
 * @author Digital Align Team
 * @reference
 * @description Application service
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global with sharing class KycReviewService extends AbstractService {
  @TestVisible
  private static KycReviewService serviceInstance;

  public KycReviewService() {
    super(KycReviewService.class);
  }

  /**
   * @description Provides a singleton instance of KycReviewService from which all other class methods can be accessed.
   * @author Digital Align Team | 01/17/2022
   * @return Object  singleton
   **/
  public static KycReviewService getInstance() {
    if (serviceInstance == null) {
      serviceInstance = (KycReviewService) getInstance(KycReviewService.class);
    }
    return serviceInstance;
  }

  //getStatusMapping
  global virtual String getStatusMapping(String fieldName, String value) {
    return (new Map<String, String>{
        'Passed' => 'Passed',
        'Failed' => 'Failed',
        'Accept' => 'Accept'
      })
      .get(value);
  }

  /**
   * @description  Primary is Existing Customer
   * Used when kyc result is return from Server
   * @author Digital Align Team | 12-07-2021
   * @param Account application
   * @param ApplicationResponseMapper.KYCResult kycResult
   * @return Account
   **/
  global virtual Account processExistingMember(
    Account application,
    ApplicationResponseMapper.KYCResult kycResult
  ) {
    log?.debug('Inside processExistingMember');
    application.isMemberFlow__c = false;
    application.ExternalApplicationNumber__c = kycResult.ExternalApplicationNumber;
    application.ExternalApplicationStatus__c = kycResult.ExternalApplicationStatus;
    application.FinServ__Status__c = ApplicationConstant.CANCELLED;
    application.mflow__Stage__c = ApplicationConstant.STAGE_EXISTING_CUSTOMER;
    application.mflow__FlowState__c = ApplicationConstant.FINAL_CONFIRMATION;
    for (Applicant__c applicant : application.Applicants__r) {
      if (
        applicant.RecordType.Name ==
        ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE
      ) {
        applicant.mflow__Status__c = ApplicationConstant.CANCELLED;
        applicant.mflow__FlowState__c = ApplicationConstant.FINAL_CONFIRMATION;
      } else {
        // #pending Joint also need to mark has cancelled
        applicant.mflow__Status__c = ApplicationConstant.CANCELLED;
        applicant.mflow__FlowState__c = ApplicationConstant.FINAL_CONFIRMATION;
      }
    }
    FinancialAccountRepository.upsertRecords(application.Applicants__r);
    FinancialAccountRepository.upsertRecord(application);
    return application;
  }

  /**
   * @description
   * @author Digital Align Team | 12-08-2021
   * @param Account application
   * @param ApplicationResponseMapper.KYCResult kycResult
   * @return Account
   **/
  global virtual Account updateApplicationKycDetails(
    Account application,
    ApplicationResponseMapper.KYCResult kycResult
  ) {
    Map<Id, Applicant__c> applicantMap = new Map<Id, Applicant__c>(
      application.Applicants__r
    );

    if (kycResult?.applicants != null) {
      for (
        ApplicationResponseMapper.KYCApplicantResult applicantKyc : kycResult.applicants
      ) {
        Applicant__c applicant = applicantMap.get(applicantKyc.ApplicantId);
        if (applicant == null) {
          continue;
        }
        applicant.CustomerNumber__c = applicantKyc.CustomerNumber;
        applicant.OverallDebitBureauResult__c = this.getStatusMapping(
          null,
          applicantKyc.OverallDebitBureauResult
        );
        applicant.CreditScore__c = applicantKyc.CreditScore;
        applicant.QualifiedScore__c = applicantKyc.QualifiedScore;
        applicant.CustomerScore__c = applicantKyc.CustomerScore;
        applicant.HighRiskConsumer__c = this.getStatusMapping(
          null,
          applicantKyc.HighRiskConsumer
        );
        applicant.QualifiedDecision__c = this.getStatusMapping(
          null,
          applicantKyc.QualifiedDecision
        );
        applicant.IdentityVerificationStatus__c = this.getStatusMapping(
          null,
          applicantKyc.IdentityVerificationStatus
        );
        applicant.OFAC__c = this.getStatusMapping(null, applicantKyc.OFAC);
        applicant.SSNValidation__c = applicantKyc.SSNValidation;
        applicant.RunWithoutKIQ__c = this.getStatusMapping(
          null,
          applicantKyc.RunWithoutKIQ
        );
        applicant.RunWithKIQ__c = this.getStatusMapping(
          null,
          applicantKyc.RunWithKIQ
        );

        //Update Applicant Status based on RunWithKIQ__c Field
        switch on applicant.RunWithKIQ__c {
          when 'Accept', 'Passed' {
            if (
              applicant.RecordType.Name ==
              ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE
            ) {
              applicant.FlowState__c = ApplicationConstant.FUNDING_WELCOME;
            }
            applicant.mflow__Status__c = ApplicationConstant.IN_PROGRESS;
            applicant.mflow__KYCStatus__c = ApplicationConstant.KYC_PASSED;
          }
          when 'Failed' {
            applicant.mflow__Status__c = ApplicationConstant.REVISION_IN_PROGRESS;
            applicant.mflow__KYCStatus__c = ApplicationConstant.KYC_FAILED;
          }
          when else {
            applicant.Status__c = ApplicationConstant.REVISION_IN_PROGRESS;
            applicant.mflow__KYCStatus__c = ApplicationConstant.KYC_UNDER_REVIEW;
          }
        }
      }
    }

    application.ExternalApplicationNumber__c = kycResult.ExternalApplicationNumber;
    application.ExternalApplicationStatus__c = kycResult.ExternalApplicationStatus;
    application.Stage__c = null;
    switch on kycResult.ExternalApplicationStatus {
      when 'Accept', 'Passed', 'Approved' {
        application.FinServ__Status__c = ApplicationConstant.IN_PROGRESS;
        application.FinServ__KYCStatus__c = ApplicationConstant.KYC_PASSED;
        application.FlowState__c = ApplicationConstant.FUNDING_WELCOME;
      }
      when 'Fraud' {
        application.FinServ__Status__c = ApplicationConstant.REVISION_IN_PROGRESS;
        application.FinServ__KYCStatus__c = ApplicationConstant.KYC_FAILED;
      }
      when else {
        application.FinServ__Status__c = ApplicationConstant.REVISION_IN_PROGRESS;
        application.FinServ__KYCStatus__c = ApplicationConstant.KYC_UNDER_REVIEW;
      }
    }
    FinancialAccountRepository.upsertRecords(application.Applicants__r);
    FinancialAccountRepository.upsertRecord(application);
    return application;
  }
}