force-app/main/default/objects/Account/fields/UserAccountType__c.field-meta.xml
<CustomField>
    <fullName>UserAccountType__c</fullName>
    <description
  >Field is used to indicate the account belong to which user type</description>
    <inlineHelpText
  >Field is used to indicate the account belong to which user type</inlineHelpText>
    <label>User Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FinancialInstituteAccount</fullName>
                <label>Financial Institute Account</label>
            </value>
             <value>
                <fullName>FinancialInstituteEmployee</fullName>
                <label>Financial Institute Employee</label>
            </value>
            <value>
                <fullName>DealerAccount</fullName>
                <label>Dealer Account</label>
            </value>
             <value>
                <fullName>CustomerApplication</fullName>
                <label>Customer Application</label>
            </value>
             <value>
                <fullName>DealerEmployee</fullName>
                <label>Dealer Employee</label>
            </value>
            <value>
                <fullName>IndividualCustomer</fullName>
                <label>Individual Customer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application for grorup MintFlow related details</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/ApplicantName__c.field-meta.xml
<CustomField>
    <fullName>ApplicantName__c</fullName>
    <description>Applicant Name</description>
    <label>Applicant Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <description>Applicant date of birth</description>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/CreditScore__c.field-meta.xml
<CustomField>
    <fullName>CreditScore__c</fullName>
    <description>To store Credit Score</description>
    <label>Credit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/CustomerScore__c.field-meta.xml
<CustomField>
    <fullName>CustomerScore__c</fullName>
    <description>To store Customer score result</description>
    <label>Customer Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First Name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/HighRiskConsumer__c.field-meta.xml
<CustomField>
    <fullName>HighRiskConsumer__c</fullName>
    <description>To store High Risk Consumer result</description>
    <label>High Risk Consumer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IdentityVerificationStatus__c.field-meta.xml
<CustomField>
    <fullName>IdentityVerificationStatus__c</fullName>
    <label>Identity Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Not Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IsEmailVerified__c.field-meta.xml
<CustomField>
    <fullName>IsEmailVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if customer email is verified</description>
    <label>Is Email Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IsPhoneNumberVerified__c.field-meta.xml
<CustomField>
    <fullName>IsPhoneNumberVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if customer phone number is verified</description>
    <label>IsPhoneNumberVerified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Customer last name</description>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/OFAC__c.field-meta.xml
<CustomField>
    <fullName>OFAC__c</fullName>
    <description>To store OFAC decision details</description>
    <label>OFAC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/OverallDebitBureauResult__c.field-meta.xml
<CustomField>
    <fullName>OverallDebitBureauResult__c</fullName>
    <description>to store Overall Debit Bureau Result</description>
    <label>Overall Debit Bureau Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/QualifiedDecision__c.field-meta.xml
<CustomField>
    <fullName>QualifiedDecision__c</fullName>
    <description>To store Qualifile result.</description>
    <label>Qualifile Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/RunWithKIQ__c.field-meta.xml
<CustomField>
    <fullName>RunWithKIQ__c</fullName>
    <description>To store Run with KIQ result</description>
    <label>Run With KIQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/RunWithoutKIQ__c.field-meta.xml
<CustomField>
    <fullName>RunWithoutKIQ__c</fullName>
    <description>To store KIQ details.</description>
    <label>Run Without KIQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>SSN number</description>
    <label>SSN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SSNValidation__c.field-meta.xml
<CustomField>
    <fullName>SSNValidation__c</fullName>
    <description>To store SSN Validation result</description>
    <label>SSN Validation</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CreditScore__c.field-meta.xml
<CustomField>
    <fullName>CreditScore__c</fullName>
    <description>To store Credit Score</description>
    <label>Credit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CustomerScore__c.field-meta.xml
<CustomField>
  <fullName>CustomerScore__c</fullName>
    <description>To store Customer score result</description>
    <label>Customer Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IdentityVerificationStatus__c.field-meta.xml
<CustomField>
    <fullName>IdentityVerificationStatus__c</fullName>
    <description>to store ID verification status</description>
    <label>Identity Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/IsEmailVerified__c.field-meta.xml
<CustomField>
    <fullName>IsEmailVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if customer email is verified</description>
    <label>IsEmailVerified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsPhoneNumberVerified__c.field-meta.xml
<CustomField>
    <fullName>IsPhoneNumberVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if customer phone number is verified</description>
    <label>IsPhoneNumberVerified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OFAC__c.field-meta.xml
<CustomField>
    <fullName>OFAC__c</fullName>
    <description>To store OFAC details.</description>
    <label>OFAC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/QualifiedDecision__c.field-meta.xml
<CustomField>
    <fullName>QualifiedDecision__c</fullName>
    <description>To store qualifile decision.</description>
    <label>Qualifile Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/RunWithKIQ__c.field-meta.xml
<CustomField>
    <fullName>RunWithKIQ__c</fullName>
    <description>To store Run with KIQ result</description>
    <label>Run With KIQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/RunwithoutKIQ__c.field-meta.xml
<CustomField>
    <fullName>RunwithoutKIQ__c</fullName>
    <description>To store KIQ details.</description>
    <label>Run without KIQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description
  >Social Security number (SSN) is issued by the Social Security Administration</description>
    <label>SSN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SSNValidation__c.field-meta.xml
<CustomField>
    <fullName>SSNValidation__c</fullName>
    <description>To store SSN Validation result</description>
    <label>SSN Validation</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserContactType__c.field-meta.xml
<CustomField>
    <fullName>UserContactType__c</fullName>
    <description
  >Field is used to indicate the contact belong to which user type</description>
    <inlineHelpText
  >Field is used to indicate the contact belong to which user type</inlineHelpText>
    <label>User Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FinancialInstituteEmployee</fullName>
                <label>Financial Institute Employee</label>
            </value>
            <value>
                <fullName>DealerEmployee</fullName>
                <label>Dealer Employee</label>
            </value>
            <value>
                <fullName>DealerAdmin</fullName>
                <label>Dealer Admin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApplicantServiceHelper.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Helper
 * @author Digital Align Team
 * @reference
 * @description Application service helper
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global virtual with sharing class ApplicantServiceHelper extends AbstractService {
  @TestVisible
  private static ApplicantServiceHelper serviceInstance;

  public ApplicantServiceHelper() {
    super(ApplicantServiceHelper.class);
  }

  /**
   * @description Provides a singleton instance of ApplicantServiceHelper from which all other class methods can be accessed.
   * @author Digital Align Team | 07-27-2021
   * @return Object  singleton
   **/
  global static ApplicantServiceHelper getInstance() {
    if (serviceInstance == null) {
      serviceInstance = (ApplicantServiceHelper) getInstance(
        ApplicantServiceHelper.class
      );
    }
    return serviceInstance;
  }

  /**
   * @description  Send Email to reference person on family connect
   * @author Digital Align Team | 11-09-2021
   **/
  global virtual void notifyFamilyConnectReference() {
    log?.debug('inside notifyFamilyConnectReference');
    try {
      List<Applicant__c> applicants = ApplicantRepository.readApplicantsByApplicationId(
        ApexRequest.getApplicationId()
      );
      CustomerEmailService.getInstance().notifyFamilyMember(applicants);
    } catch (exception ex) {
      log?.error(ex);
    }
  }

  /**
   * @description Create Individual Account and Contact in salesforce
   * @author Digital Align Team | 12-10-2021
   * @param Applicant__c applicant
   * @return Contact
   **/
  //#removeFSC
  /*
  global virtual Contact createAccount(Applicant__c applicant) {
    Account individualAccount = new Account();
    individualAccount.Name = applicant.ApplicantName__c;
    individualAccount.RecordTypeId = SObjectUtils.recordTypeIdByDevName(
      Account.SObjectType,
      'IndustriesIndividual'
    );
    // #info
    // Added for customer community user license only
    // Work for Cusotmer Community plus user without owner assingment
    //individualAccount.OwnerId = UserUtils.getCurrentUser().CreatedById;
    individualAccount.UserAccountType__c = 'IndividualCustomer';
    ApplicantRepository.upsertRecord(individualAccount);
    // Return Individual Contact created by Salesforce , when account is created
    return ApplicantRepository.fetchContactByAccountId(individualAccount.Id);
  } */

  /**
   * @description map applicant data with contact data
   * @author Digital Align Team | 12-10-2021
   * @param Applicant__c applicant
   * @param Contact memberContact
   * @param Boolean isExistingContact
   * @return Contact
   **/
  global virtual Contact mapApplicantWithContact(
    Applicant__c applicant,
    Contact memberContact,
    Boolean isExistingContact
  ) {
    if (!isExistingContact) {
      memberContact.FirstName = applicant.FirstName__c;
      memberContact.LastName = applicant.LastName__c;
      memberContact.FinServ__TaxId__c = applicant.SSN__c;
    }
    memberContact.UserContactType__c = 'IndividualCustomer';
    memberContact.Email = applicant.Email__c;
    memberContact.Phone = applicant.Phone__c;
    memberContact.FinServ__EmailVerified__c = applicant.IsEmailVerified__c;
    memberContact.FinServ__HomePhoneVerified__c = applicant.IsPhoneNumberVerified__c;
    memberContact.FinServ__LastFourDigitSSN__c = applicant.SSN__c.right(4);
    memberContact.RunWithKIQ__c = applicant.RunWithKIQ__c;
    memberContact.RunWithoutKIQ__c = applicant.RunWithoutKIQ__c;
    memberContact.IdentityVerificationStatus__c = applicant.IdentityVerificationStatus__c;
    memberContact.Birthdate = applicant.Birthdate__c;
    memberContact.SSNValidation__c = applicant.SSNValidation__c;
    memberContact.CreditScore__c = applicant.CreditScore__c;
    memberContact.CustomerScore__c = applicant.CustomerScore__c;
    memberContact.HighRiskConsumer__c = applicant.HighRiskConsumer__c;
    memberContact.OFAC__c = applicant.OFAC__c;
    memberContact.OverallDebitBureauResult__c = applicant.OverallDebitBureauResult__c;
    memberContact.QualifiedDecision__c = applicant.QualifiedDecision__c;
    memberContact.QualifiedScore__c = applicant.QualifiedScore__c;
    memberContact.FraudStatus__c = applicant.FraudStatus__c;
    memberContact.IncomeVerificationStatus__c = applicant.IncomeVerificationStatus__c;
    memberContact.KYCStatus__c = applicant.KYCStatus__c;
    memberContact.SentiLinkFraudScore__c = applicant.SentiLinkFraudScore__c;
    memberContact.SentiLinkStatus__c = applicant.SentiLinkStatus__c;
    memberContact.MiddleName__c = applicant.MiddleName__c;
    return memberContact;
  }
}