force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Address object for saving address of different types across objects</description>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>state of the address</description>
    <label>State</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <description>State code of the address</description>
    <label>State Code</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerActionsFramework/AddressTriggerHandler.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Service
 * @author Digital Align Team
 * @reference
 * @description Application service
 **/
public with sharing class AddressTriggerHandler extends AbstractTriggerHandler {
  public AddressTriggerHandler() {
    super(AddressTriggerHandler.class);
  }

  /**
   * @description
   * @author Digital Align | 01-03-2022
   **/
  public override void beforeInsert() {
    List<Address__c> addresses = (List<Address__c>) Trigger.new;
    saveAddresses(addresses);
  }

  /**
   * @description
   * @author Digital Align | 01-03-2022
   **/
  public override void beforeUpdate() {
    List<Address__c> addresses = (List<Address__c>) Trigger.new;
    saveAddresses(addresses);
  }

  /**
   * @description
   * @author Digital Align | 01-03-2022
   * @param List<Address> addresses
   * @return List<Address__c>
   **/
  public List<Address__c> saveAddresses(List<Address__c> addresses) {
    for (Address__c address : addresses) {
      if (String.isNotBlank(address.StateCode__c)) {
        address.State__c = GenericUtils.fetchStateFromStateCode(address.StateCode__c);
      }
    }
    return addresses;
  }
}