force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IdentificationDocument__c.field-meta.xml
<CustomField>
    <fullName>IdentificationDocument__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Object to store all identity details</description>
    <label>Identification Document</label>
    <referenceTo>FinServ__IdentificationDocument__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/recordTypes/Primary.recordType-meta.xml
<RecordType>
    <fullName>Primary</fullName>
    <active>true</active>
    <description>Primary Applicant</description>
    <label>Primary</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fsc-app/main/default/objects/FinServ__IdentificationDocument__c/FinServ__IdentificationDocument__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__IdentificationDocumentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about documents used to verify a person&apos;s identity.</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>DOC-{000000000}</displayFormat>
        <label>Document</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IdentificationDocument__c/IdentificationDocument__c.object-meta.xml
<CustomObject>
    <description>Identification Document for Applicants</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/test/default/classes/ApplicationSubmissionServiceTest.cls
@istest
public with sharing class ApplicationSubmissionServiceTest {
  private static Application__c makeApplicationData() {
    Application__c acc = TestData.createApplication();
    acc = (Application__c) DatabaseUtils.insertRecord(acc);

    Applicant__c applicant = TestData.createApplicant('Primary');
    applicant.Application__c = acc.Id;
    applicant = (Applicant__c) DatabaseUtils.insertRecord(applicant);

    IdentificationDocument__c identity = TestData.createIdentity(null);
    identity.Applicant__c = applicant.Id;
    identity = (IdentificationDocument__c) DatabaseUtils.insertRecord(identity);
    applicant.mflow__IdentificationDocuments__r.addAll(new List<IdentificationDocument__c>{ identity });
    acc.Applicants__r.addAll(new List<Applicant__c>{ applicant });
    return acc;
  }
  @istest
  private static void testOne() {
    Application__c application = makeApplicationData();
    string data = 'data';
    ApplicationSubmissionService.getInstance().submitApplication(data);
  }
}