force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IdentificationDocument__c.field-meta.xml
<CustomField>
    <fullName>IdentificationDocument__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Object to store all identity details</description>
    <label>Identification Document</label>
    <referenceTo>FinServ__IdentificationDocument__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/recordTypes/Primary.recordType-meta.xml
<RecordType>
    <fullName>Primary</fullName>
    <active>true</active>
    <description>Primary Applicant</description>
    <label>Primary</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerInterest__c/CustomerInterest__c.object-meta.xml
<CustomObject>
    <description>Object store store cross sell product details selected by customers.</description>
    <label>Customer Interest</label>
    <nameField>
        <label>Customer Interest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerInterest__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Application</description>
    <label>Application</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Interests</relationshipLabel>
    <relationshipName>Customer_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerInterest__c/fields/InterestProduct__c.field-meta.xml
<CustomField>
    <fullName>InterestProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Interested product of customer</description>
    <label>Interest Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Customer Interests</relationshipLabel>
    <relationshipName>CustomerInterests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/FinancialAccount__c.object-meta.xml
<CustomObject>
    <description
  >A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Financial Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DAT-200</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>related product</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/recordTypes/Savings.recordType-meta.xml
<RecordType>
    <fullName>Savings</fullName>
    <active>true</active>
    <description>Saving Financial Account</description>
    <label>Savings</label>
</RecordType>

force-app/main/default/objects/FinancialAccountTransaction__c/FinancialAccountTransaction__c.object-meta.xml
<CustomObject>
    <description
  >Represents information about financial account transactions.</description>
    <label>Financial Account Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccountTransaction__c/fields/FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Financial Account</description>
    <label>Financial Account</label>
    <referenceTo>FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Transactions</relationshipLabel>
    <relationshipName>FinancialAccountTranslations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialProduct__c/FinancialProduct__c.object-meta.xml
<CustomObject>
    <description>Object to store all product related data</description>
    <label>Financial Product</label>
    <nameField>
        <label>FinancialProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fsc-app/main/default/objects/FinServ__IdentificationDocument__c/FinServ__IdentificationDocument__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__IdentificationDocumentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about documents used to verify a person&apos;s identity.</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>DOC-{000000000}</displayFormat>
        <label>Document</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IdentificationDocument__c/IdentificationDocument__c.object-meta.xml
<CustomObject>
    <description>Identification Document for Applicants</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductService__c/ProductService__c.object-meta.xml
<CustomObject>
    <description>Available Product services for products</description>
    <label>Product Service</label>
    <nameField>
        <label>Product Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductService__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to product object</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Product Services</relationshipLabel>
    <relationshipName>ProductServices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/test/default/classes/FinancialAccountServiceTest.cls
@istest
public with sharing class FinancialAccountServiceTest {
  private static Application__c makeApplicationData() {
    Application__c acc = TestData.createApplication();
    acc = (Application__c) DatabaseUtils.insertRecord(acc);

    List<FinancialProduct__c> products = TestData.createProduct();
    products = (List<FinancialProduct__c>) DatabaseUtils.insertRecords(products);

    ProductService__c productService = TestData.makeProductService();
    productService.mflow__FinancialProduct__c = products[0].Id;
    productService = (ProductService__c) DatabaseUtils.insertRecord(productService);

    FinancialAccount__c finAcc = TestData.makeFinancialAccount();
    finAcc.mflow__FinancialProduct__c = products[0].Id;
    finAcc.mflow__Application__c = acc.Id;
    Id recType = Schema.SObjectType.FinancialAccount__c.getRecordTypeInfosByName().get('Savings').getRecordTypeId();
    finAcc.RecordTypeId = recType;
    finAcc = (FinancialAccount__c) DatabaseUtils.insertRecord(finAcc);

    FinancialAccountTransaction__c tran = TestData.createFinancialAccountTransaction();
    tran.FinancialAccount__c = finAcc.Id;
    tran.TransactionDate__c = DateTime.newInstance(2007, 6, 23, 3, 3, 3);
    tran = (FinancialAccountTransaction__c) DatabaseUtils.insertRecord(tran);

    Applicant__c applicant = TestData.createApplicant('Primary');
    applicant.Application__c = acc.Id;
    applicant = (Applicant__c) DatabaseUtils.insertRecord(applicant);

    acc.Applicants__r.addAll(new List<Applicant__c>{ applicant });
    IdentificationDocument__c identity = TestData.createIdentity();
    identity.Applicant__c = applicant.Id;
    identity = (IdentificationDocument__c) DatabaseUtils.insertRecord(identity);
    applicant.mflow__IdentificationDocuments__r.addAll(new List<IdentificationDocument__c>{ identity });
    acc.mflow__FinancialAccounts__r.addAll(new List<FinancialAccount__c>{ finAcc });
    acc.mflow__CustomerInterests__r.addAll(new List<mflow__CustomerInterest__c>{ new mflow__CustomerInterest__c() });
    return acc;
  }
  @isTest
  static void testOne() {
    test.startTest();
    // FinancialAccountService.
    test.stopTest();
  }
}