force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/ApplicantType__c.field-meta.xml
<CustomField>
    <fullName>ApplicantType__c</fullName>
    <description>Describes applicant type primary or joint</description>
    <label>Applicant Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Joint</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Emergency Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant__c/recordTypes/FamilyMember.recordType-meta.xml
<RecordType>
    <fullName>FamilyMember</fullName>
    <active>true</active>
    <description>Family Member</description>
    <label>Family Member</label>
</RecordType>

force-app/main/default/objects/Applicant__c/recordTypes/Joint.recordType-meta.xml
<RecordType>
    <fullName>Joint</fullName>
    <active>true</active>
    <description>Joint Applicant</description>
    <label>Joint</label>
</RecordType>

force-app/main/default/objects/Applicant__c/recordTypes/Primary.recordType-meta.xml
<RecordType>
    <fullName>Primary</fullName>
    <active>true</active>
    <description>Primary Applicant</description>
    <label>Primary</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationConfiguration__c/ApplicationConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Configuration</label>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/FinancialAccount__c.object-meta.xml
<CustomObject>
    <description
  >A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Financial Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DAT-200</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>related product</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialProduct__c/FinancialProduct__c.object-meta.xml
<CustomObject>
    <description>Object to store all product related data</description>
    <label>Financial Product</label>
    <nameField>
        <label>FinancialProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/CustomerEmailServiceTest.cls
@IsTest
public with sharing class CustomerEmailServiceTest {
  private static Application__c makeAccountData() {
    Application__c acc = TestData.createApplication();
    acc = (Application__c) DatabaseUtils.insertRecord(acc);
    return acc;
  }
  private static List<FinancialProduct__c> makeProducts() {
    List<FinancialProduct__c> products = TestData.createProduct();
    products = (List<FinancialProduct__c>) DatabaseUtils.insertRecords(products);
    return products;
  }
  private static Applicant__c makeApplicantData() {
    Application__c acc = TestData.createApplication();
    acc = (Application__c) DatabaseUtils.insertRecords(new List<Application__c>{ acc })[0];
    Applicant__c applicant = TestData.createApplicant(acc.Id);
    applicant.Email__c = 'test@mail.com';
    applicant = (Applicant__c) DatabaseUtils.insertRecord(applicant);
    return applicant;
  }
  private static List<Applicant__c> makeApplicantList(string applicantType) {
    Applicant__c primary = makeApplicantData();
    Id recType = Schema.SObjectType.Applicant__c.getRecordTypeInfosByName().get('Primary').getRecordTypeId();
    primary.RecordTypeId = recType;
    Applicant__c familyMember = TestData.createApplicant(primary.Application__c);
    familyMember.Email__c = 'test@mail.com';
    familyMember.ApplicantType__c = applicantType;
    familyMember = (Applicant__c) DatabaseUtils.insertRecord(familyMember);
    return (new List<Applicant__c>{ primary, familyMember });
  }
  private static ApplicationConfiguration__c makeApplicationConfiguration() {
    ApplicationConfiguration__c appConfig = TestData.createApplicationConfiguration();
    appConfig = (ApplicationConfiguration__c) DatabaseUtils.insertRecord(appConfig);
    return appConfig;
  }
  private static Applicant__c makeApplicantDataWithoutEmail() {
    Application__c acc = TestData.createApplication();
    acc = (Application__c) DatabaseUtils.insertRecords(new List<Application__c>{ acc })[0];
    Applicant__c applicant = TestData.createApplicant(acc.Id);
    applicant = (Applicant__c) DatabaseUtils.insertRecord(applicant);
    return applicant;
  }

  @IsTest
  private static void validatGeneralEmails() {
    Applicant__c applicant = makeApplicantData();
    makeApplicationConfiguration();
    Test.startTest();
    CustomerEmailService.getInstance().sendEmailOTP(applicant);
    CustomerEmailService.getInstance().savedApplication(applicant);
    CustomerEmailService.getInstance().resumeApplication(applicant);
    CustomerEmailService.getInstance().notifyAboutEmploymentReport(applicant, 'Notify');
    CustomerEmailService.getInstance().uploadIdentityDocument(applicant);
    CustomerEmailService.getInstance().accountOpened(applicant, new FinancialAccount__c());
    CustomerEmailService.getInstance().primaryReviewInformationCompleted(applicant);
    Test.stopTest();
    System.assertEquals(0, Limits.getEmailInvocations(), 'success');
  }

  @IsTest
  private static void validatFamilyNotificationEmail() {
    List<Applicant__c> applicants = makeApplicantList('Family Member');
    Test.startTest();
    CustomerEmailService.getInstance().removeJointApplicant(applicants);
    CustomerEmailService.getInstance().notifyFamilyMember(applicants);
    Test.stopTest();
    System.assertEquals(0, Limits.getEmailInvocations(), 'success');
  }
  @IsTest
  private static void validatReviewInformationSubmittedOne() {
    makeApplicationConfiguration();
    List<Applicant__c> applicants = makeApplicantList('Joint');
    List<String> notifications = new List<String>{ 'PrimaryReviewInformationSubmitted', 'JointStartApplication' };
    Test.startTest();
    for (string notificationType : notifications) {
      CustomerEmailService.getInstance().reviewInformationSubmitted(applicants, notificationType);
    }
    Test.stopTest();
    System.assertEquals(0, Limits.getEmailInvocations(), 'success');
  }
  @IsTest
  private static void validateEmailNotSent() {
    Applicant__c applicant = makeApplicantDataWithoutEmail();
    Test.startTest();
    try {
      CustomerEmailService.getInstance().sendEmailOTP(applicant);
    } catch (Exception e) {
      System.assertEquals(e.getMessage(), 'email not sent');
    }
    Test.stopTest();
  }
  @IsTest
  private static void validateProductEmails() {
    Applicant__c applicant = makeApplicantData();
    Application__c app = makeAccountData();
    List<FinancialProduct__c> products = makeProducts();
    app.Applicants__r.addAll(makeApplicantList('Primary'));
    makeApplicationConfiguration();
    Test.startTest();
    try {
      CustomerEmailService.getInstance().fundingLinkOnKycApproval(app);
      CustomerEmailService.getInstance().startSecondaryApplication(applicant, products);
    } catch (Exception e) {
      System.assertEquals(e.getMessage(), 'email not sent');
    }
    Test.stopTest();
  }
}