force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactPointAddress/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and contact point address</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Contact Point Addresses</relationshipLabel>
    <relationshipName>ContactPointAddresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__Employment__c/FinServ__Employment__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__EmploymentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about a person&apos;s employment history.</description>
    <label>Employment</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and Employment realtionship</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Employment</relationshipLabel>
    <relationshipName>Employments</relationshipName>
    <type>Lookup</type>
</CustomField>

fsc-app/main/default/objects/FinServ__IdentificationDocument__c/FinServ__IdentificationDocument__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__IdentificationDocumentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about documents used to verify a person&apos;s identity.</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>DOC-{000000000}</displayFormat>
        <label>Document</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IdentificationDocument__c/IdentificationDocument__c.object-meta.xml
<CustomObject>
    <description>Identification Document for Applicants</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Alloy/AlloyRepository.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Repository
 * @author Digital Align Team
 * @reference
 * @description
 **/
global with sharing class AlloyRepository extends DatabaseUtils {
  /**
   * @description read  applicant with child record
   * @author Digital Align Team | 10-26-2021
   * @param Applicant__c applicantId
   **/
  global static Applicant__c readApplicantWithChild(Id applicantId) {
    Query qry = Query.newInstance(Applicant__c.SObjectType)
      .addFields()
      .queryChild('mflow__IdentificationDocuments__r')
      .addFields()
      .orderBy('mflow__Order__c')
      .run()
      .queryChild('mflow__ContactPointAddresses__r')
      .addFields()
      .removeFields('Address')
      .orderBy('mflow__Order__c')
      .run()
      .queryChild('mflow__Employments__r')
      .addFields()
      .orderBy('mflow__Order__c')
      .run()
      .whereEq('Id', applicantId);
    return (Applicant__c) DatabaseUtils.getRecord(qry.toString());
  }
}