force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/ApplicantType__c.field-meta.xml
<CustomField>
    <fullName>ApplicantType__c</fullName>
    <description>Describes applicant type primary or joint</description>
    <label>Applicant Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Joint</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Emergency Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/EmailOtp__c.field-meta.xml
<CustomField>
    <fullName>EmailOtp__c</fullName>
    <description>To store Email Otp</description>
    <label>Email Otp</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IdentificationDocument__c.field-meta.xml
<CustomField>
    <fullName>IdentificationDocument__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Object to store all identity details</description>
    <label>Identification Document</label>
    <referenceTo>FinServ__IdentificationDocument__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/OTPExpireTime__c.field-meta.xml
<CustomField>
    <fullName>OTPExpireTime__c</fullName>
    <description>OTP expire time</description>
    <inlineHelpText>OTP expire time</inlineHelpText>
    <label>OTP Expire Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SmsOtp__c.field-meta.xml
<CustomField>
    <fullName>SmsOtp__c</fullName>
    <description>To store OTP</description>
    <label>Sms OTP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>SSN number</description>
    <label>SSN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/recordTypes/FamilyMember.recordType-meta.xml
<RecordType>
    <fullName>FamilyMember</fullName>
    <active>true</active>
    <description>Family Member</description>
    <label>Family Member</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationConfiguration__c/ApplicationConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Configuration</label>
</CustomObject>

force-app/main/default/objects/ApplicationConfiguration__c/fields/AllowedOtpMode__c.field-meta.xml
<CustomField>
    <fullName>AllowedOtpMode__c</fullName>
    <description>Allowed different OTP veriifcation</description>
    <inlineHelpText>Enter value by comma seperated, Ex SMS;EMAIL</inlineHelpText>
    <label>Allowed Otp Mode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description
  >Social Security number (SSN) is issued by the Social Security Administration</description>
    <label>SSN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactPointAddress/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and contact point address</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Contact Point Addresses</relationshipLabel>
    <relationshipName>ContactPointAddresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employment__c/Employment__c.object-meta.xml
<CustomObject>
    <description
  >Represents information about a person&apos;s employment history.</description>
    <label>Employment</label>
    <nameField>
        <displayFormat>Emp-{00000}</displayFormat>
        <label>Employment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialProduct__c/FinancialProduct__c.object-meta.xml
<CustomObject>
    <description>Object to store all product related data</description>
    <label>Financial Product</label>
    <nameField>
        <label>FinancialProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/FinServ__Employment__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__EmploymentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about a person&apos;s employment history.</description>
    <label>Employment</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and Employment realtionship</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Employment</relationshipLabel>
    <relationshipName>Employments</relationshipName>
    <type>Lookup</type>
</CustomField>

fsc-app/main/default/objects/FinServ__IdentificationDocument__c/FinServ__IdentificationDocument__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__IdentificationDocumentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about documents used to verify a person&apos;s identity.</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>DOC-{000000000}</displayFormat>
        <label>Document</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IdentificationDocument__c/IdentificationDocument__c.object-meta.xml
<CustomObject>
    <description>Identification Document for Applicants</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SystemSetting__c/SystemSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>System Setting</label>
</CustomObject>

force-app/test/default/classes/ApplicantControllerTest.cls
@istest
public with sharing class ApplicantControllerTest {
  private static void makeApplicationConfiguration() {
    ApplicationConfiguration__c appConfig = TestData.createApplicationConfiguration();
    insert appConfig;
    SystemSetting__c systemSetting = TestData.createSystemSetting();
    insert systemSetting;
    List<FinancialProduct__c> products = TestData.createProduct();
    insert products;
  }

  private static Applicant__c createApplicantDataWithChild(Application__c Application) {
    Applicant__c applicant = TestData.createApplicant(Application.Id);
    insert Applicant;
    SObjectConstructor construct = SObjectConstructor.getInstance(applicant);

    IdentificationDocument__c identity = TestData.createIdentity(applicant.Id);
    insert identity;

    Employment__c employment = TestData.createEmployment(applicant.Id);
    insert employment;

    ContactPointAddress address = TestData.createContactPointAddress(applicant.Id);
    insert address;

    construct.addChildObject('mflow__IdentificationDocuments__r', identity);
    construct.addChildObject('mflow__Employments__r', employment);
    construct.addChildObject('mflow__ContactPointAddresses__r', address);

    return (Applicant__c) construct.build();
  }
  private static void createExistingContact(string ssn) {
    Contact con = testdata.createContact(null);
    con.mflow__SSN__c = ssn;
    upsert con;
  }

  @isTest
  static void readApplicantTest() {
    makeApplicationConfiguration();
    Application__c app = TestData.createApplication();
    insert app;
    Applicant__c applicant = createApplicantDataWithChild(app);
    String token = SecurityUtils.generateTokenForTesting(
      app.Id,
      applicant.id,
      ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE,
      ApplicationConstant.FLOW_TYPE_APPLICATION
    );

    //200
    ApexRequest request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'applicantIds' => new List<String>{ applicant.Id } });
    request.token = token;
    ApexResponse res = ApplicantController.readApplicantsWithChild(request);
    system.assertEquals(200, res.status, 'success');

    //500
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'applicantIds' => new List<String>{ applicant.Id } });
    request.token = 'invalidToken';
    res = ApplicantController.readApplicantsWithChild(request);
    system.assertEquals(500, res.status, 'success');

    //400
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'applicantIds' => new Map<String, String>{ 'key' => 'value' } });
    request.token = token;
    res = ApplicantController.readApplicantsWithChild(request);
    system.assertEquals(400, res.status, 'success');

    //Applicant Service Read
    ApplicantService.getInstance().readApplicantWithChild(applicant.Id);
  }

  @isTest
  static void saveApplicantsTest() {
    makeApplicationConfiguration();
    Application__c app = TestData.createApplication();
    insert app;
    Applicant__c applicant = createApplicantDataWithChild(app);
    String token = SecurityUtils.generateTokenForTesting(
      app.Id,
      applicant.id,
      ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE,
      ApplicationConstant.FLOW_TYPE_APPLICATION
    );

    ApexRequest request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'applicantIds' => new List<String>{ applicant.Id } });
    request.token = token;
    ApexResponse res = ApplicantController.readApplicantsWithChild(request);
    system.assertEquals(200, res.status, 'success');
    //200
    request = new ApexRequest();
    request.token = token;
    request.data = (String) res.data;
    res = ApplicantController.saveApplicants(request);
    system.assertEquals(200, res.status, 'success');
    //500
    request = new ApexRequest();
    request.token = 'invalidToken';
    request.data = (String) res.data;
    res = ApplicantController.saveApplicants(request);
    system.assertEquals(500, res.status, 'success');

    //400
    request = new ApexRequest();
    request.token = token;
    request.data = (String) '{}';
    res = ApplicantController.saveApplicants(request);
    system.assertEquals(400, res.status, 'success');
  }

  @isTest
  static void saveApplicantTest() {
    makeApplicationConfiguration();
    Application__c app = TestData.createApplication();
    insert app;
    Applicant__c applicant = createApplicantDataWithChild(app);
    String token = SecurityUtils.generateTokenForTesting(
      app.Id,
      applicant.id,
      ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE,
      ApplicationConstant.FLOW_TYPE_APPLICATION
    );

    ApexRequest request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'applicantIds' => new List<String>{ applicant.Id } });
    request.token = token;
    ApexResponse res = ApplicantController.readApplicantsWithChild(request);
    system.assertEquals(200, res.status, 'success');

    List<Object> applicants = (List<Object>) Json.deserializeUntyped((String) res.data);
    String applicantJson = Json.serialize(applicants[0]);
    //200
    request = new ApexRequest();
    request.token = token;
    request.data = applicantJson;
    res = ApplicantController.saveApplicant(request);
    system.assertEquals(200, res.status, 'success');
    //500
    request = new ApexRequest();
    request.token = 'invalidToken';
    request.data = applicantJson;
    res = ApplicantController.saveApplicant(request);
    system.assertEquals(500, res.status, 'success');

    //400
    request = new ApexRequest();
    request.token = token;
    request.data = (String) '[]';
    res = ApplicantController.saveApplicant(request);
    system.assertEquals(400, res.status, 'success');
  }

  @isTest
  static void generateOTPTest() {
    makeApplicationConfiguration();
    Application__c app = TestData.createApplication();
    insert app;
    Applicant__c applicant = createApplicantDataWithChild(app);
    applicant.Email__c = 'test@test.com';
    applicant.Phone__c = '9876543210';
    upsert applicant;
    String token = SecurityUtils.generateTokenForTesting(
      app.Id,
      applicant.id,
      ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE,
      ApplicationConstant.FLOW_TYPE_APPLICATION
    );

    //400 OTP Generate custom Exception
    ApexRequest request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'applicantId' => 'invalidID' });
    request.token = token;
    ApexResponse res = ApplicantController.generateOTP(request);
    system.assertEquals(400, res.status, 'success');

    //200
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new MockAPIResponse('SampleRequest', '200'));
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'applicantId' => applicant.Id });
    request.token = token;
    res = ApplicantController.generateOTP(request);
    system.assertEquals(200, res.status, 'success');
    Test.stopTest();
  }

  @isTest
  static void validateOTPTest() {
    makeApplicationConfiguration();
    Application__c app = TestData.createApplication();
    insert app;
    Applicant__c applicant = createApplicantDataWithChild(app);
    applicant.Email__c = 'test@test.com';
    applicant.Phone__c = '9876543210';
    upsert applicant;
    String token = SecurityUtils.generateTokenForTesting(
      app.Id,
      applicant.id,
      ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE,
      ApplicationConstant.FLOW_TYPE_APPLICATION
    );

    //200
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new MockAPIResponse('SampleRequest', '200'));
    ApexRequest request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'applicantId' => applicant.Id });
    request.token = token;
    ApexResponse res = ApplicantController.generateOTP(request);
    system.assertEquals(200, res.status, 'success');
    Test.stopTest();

    //200
    //#1
    applicant = [SELECT id, SmsOtp__c, EmailOtp__c FROM mflow__Applicant__c WHERE id = :applicant.id];
    request = new ApexRequest();
    request.setHeader(
      new Map<String, object>{
        'sms' => applicant.SmsOtp__c,
        'email' => applicant.EmailOtp__c,
        'applicantId' => applicant.Id
      }
    );
    request.token = token;
    res = ApplicantController.validateOTP(request);
    system.assertEquals(200, res.status, 'success');
    //400
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'applicantId' => 'invalidId' });
    request.token = token;
    res = ApplicantController.validateOTP(request);
    system.assertEquals(400, res.status, 'success');

    ApplicationConfiguration__c appConfig = [SELECT AllowedOtpMode__c FROM ApplicationConfiguration__c LIMIT 1];
    //500
    //#2 Empty EMail
    appConfig.AllowedOtpMode__c = 'EMAIL';
    update appConfig;
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'email' => '', 'applicantId' => applicant.Id });
    request.token = token;
    res = ApplicantController.validateOTP(request);
    system.assertEquals(500, res.status, 'success');

    //#3 Empty sms
    appConfig.AllowedOtpMode__c = 'SMS';
    update appConfig;
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'sms' => '', 'applicantId' => applicant.Id });
    request.token = token;
    res = ApplicantController.validateOTP(request);
    system.assertEquals(500, res.status, 'success');

    //#4 Invalid EMail
    appConfig.AllowedOtpMode__c = 'EMAIL';
    update appConfig;
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'email' => '323', 'applicantId' => applicant.Id });
    request.token = token;
    res = ApplicantController.validateOTP(request);
    system.assertEquals(500, res.status, 'success');

    //#5 Invalid sms
    appConfig.AllowedOtpMode__c = 'SMS';
    update appConfig;
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'sms' => '232', 'applicantId' => applicant.Id });
    request.token = token;
    res = ApplicantController.validateOTP(request);
    system.assertEquals(500, res.status, 'success');

    applicant.SmsOtp__c = '1111';
    applicant.EmailOtp__c = '1111';
    update applicant;
    //#6 valid EMail
    appConfig.AllowedOtpMode__c = 'EMAIL';
    update appConfig;
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'email' => '1111', 'applicantId' => applicant.Id });
    request.token = token;
    res = ApplicantController.validateOTP(request);
    system.assertEquals(200, res.status, 'success');

    //#7 valid sms
    appConfig.AllowedOtpMode__c = 'SMS';
    update appConfig;
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'sms' => '1111', 'applicantId' => applicant.Id });
    request.token = token;
    res = ApplicantController.validateOTP(request);
    system.assertEquals(200, res.status, 'success');

    //#8 Max Attempta
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'sms' => '2222', 'applicantId' => applicant.Id });
    request.token = token;
    res = ApplicantController.validateOTP(request);
    system.assertEquals(500, res.status, 'success');

    //#9 expire OTP
    applicant.OTPExpireTime__c = Datetime.now().addMinutes(-10);
    update applicant;
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'otpMode' => 'SMS', 'sms' => '1111', 'applicantId' => applicant.Id });
    request.token = token;
    res = ApplicantController.validateOTP(request);
    system.assertEquals(500, res.status, 'success');
  }

  @isTest
  static void atomicAuthenticateTest() {
    makeApplicationConfiguration();
    Application__c app = TestData.createApplication();
    insert app;
    Applicant__c applicant = createApplicantDataWithChild(app);
    String token = SecurityUtils.generateTokenForTesting(
      app.Id,
      applicant.id,
      ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE,
      ApplicationConstant.FLOW_TYPE_APPLICATION
    );

    //400 Exception // no Mock API
    ApexRequest request = new ApexRequest();
    request.setHeader(
      new Map<String, object>{ 'applicantId' => applicant.Id, 'employerId' => applicant.Employments__r[0].Id }
    );
    request.token = token;
    ApexResponse res = ApplicantController.atomicAuthenticate(request);
    system.assertEquals(400, res.status, 'success');

    // 200
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new MockAPIResponse('AtomicFIRequest', '200'));
    request = new ApexRequest();
    request.setHeader(
      new Map<String, object>{ 'applicantId' => applicant.Id, 'employerId' => applicant.Employments__r[0].Id }
    );
    request.token = token;
    res = ApplicantController.atomicAuthenticate(request);
    system.assertEquals(200, res.status, 'success');
    Test.stopTest();
  }

  @isTest
  static void getAtomicResponseTest() {
    makeApplicationConfiguration();
    Application__c app = TestData.createApplication();
    insert app;
    Applicant__c applicant = createApplicantDataWithChild(app);
    String token = SecurityUtils.generateTokenForTesting(
      app.Id,
      applicant.id,
      ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE,
      ApplicationConstant.FLOW_TYPE_APPLICATION
    );

    //400 Exception // no Mock API
    ApexRequest request = new ApexRequest();
    request.setHeader(
      new Map<String, object>{ 'applicantId' => applicant.Id, 'employerId' => applicant.Employments__r[0].Id }
    );
    request.token = token;
    ApexResponse res = ApplicantController.getAtomicResponse(request);
    system.assertEquals(200, res.status, 'success');

    //CReate NEw File for Atomicfic
    //FileService.getInstance().createFile
    FileService.getInstance()
      .createFile(
        new FileDTO('test.txt', blob.valueof('test'), applicant.Employments__r[0].Id, 'Employment', 'AtomicFIResponse')
      );

    request = new ApexRequest();
    request.setHeader(
      new Map<String, object>{ 'applicantId' => applicant.Id, 'employerId' => applicant.Employments__r[0].Id }
    );
    request.token = token;
    res = ApplicantController.getAtomicResponse(request);
    system.assertEquals(200, res.status, 'success');

    //exception case
    request = new ApexRequest();
    request.setHeader(
      new Map<String, object>{ 'applicantId' => 'invalidID', 'employerId' => applicant.Employments__r[0].Id }
    );
    request.token = token;
    res = ApplicantController.getAtomicResponse(request);
    system.assertEquals(400, res.status, 'success');
  }

  @isTest
  static void generatePaySlipsW2Test() {
    makeApplicationConfiguration();
    Application__c app = TestData.createApplication();
    insert app;
    Applicant__c applicant = createApplicantDataWithChild(app);
    String token = SecurityUtils.generateTokenForTesting(
      app.Id,
      applicant.id,
      ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE,
      ApplicationConstant.FLOW_TYPE_APPLICATION
    );

    //400 Exception // no Mock API
    ApexRequest request = new ApexRequest();
    request.setHeader(
      new Map<String, object>{ 'applicantId' => applicant.Id, 'employerId' => applicant.Employments__r[0].Id }
    );
    request.token = token;
    ApexResponse res = ApplicantController.generatePaySlipsW2(request);
    system.assertEquals(400, res.status, 'success');
  }

  @isTest
  static void validateAtomicFiTest() {
    makeApplicationConfiguration();
    Application__c app = TestData.createApplication();
    insert app;
    Applicant__c applicant = createApplicantDataWithChild(app);
    String token = SecurityUtils.generateTokenForTesting(
      app.Id,
      applicant.id,
      ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE,
      ApplicationConstant.FLOW_TYPE_APPLICATION
    );

    //200
    ApexRequest request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'employerId' => applicant.Employments__r[0].Id });
    request.token = token;
    ApexResponse res = ApplicantController.validateAtomicFi(request);
    system.assertEquals(200, res.status, 'success');
  }

  /** Application Service  */
  @isTest
  static void afterSaveApplicantsTest() {
    makeApplicationConfiguration();
    List<FinancialProduct__c> products = TestData.createProduct();
    insert products;
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());

    Applicant__c familyMember = TestData.createApplicant(application.id);
    familyMember.ApplicantType__c = 'Family Member';
    familyMember.Email__c = 'test@test.com';
    familyMember.Phone__c = '9876543210';
    insert familyMember;

    //200
    ApexRequest request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'applicantIds' => new List<String>{ ApexRequest.getApplicantId() } });
    request.token = ApexRequest.getToken();
    ApexResponse res = ApplicantController.readApplicantsWithChild(request);
    system.assertEquals(200, res.status, 'success');

    //Save Applicant
    List<Object> applicants = (List<Object>) Json.deserializeUntyped((String) res.data);
    String applicantJson = Json.serialize(applicants[0]);
    //200
    request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.currentPage = 'PersonalInfo';
    request.data = applicantJson;
    res = ApplicantController.saveApplicant(request);
    system.assertEquals(200, res.status, 'success');

    //200 //saveApplicants
    request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.data = (String) Json.serialize(applicants);
    request.currentPage = 'PersonalInfo';
    res = ApplicantController.saveApplicants(request);
    system.assertEquals(200, res.status, 'success');
  }

  @isTest
  static void verifyKYCTest() {
    makeApplicationConfiguration();
    Application__c app = TestData.createApplication();
    insert app;
    Applicant__c applicant = createApplicantDataWithChild(app);
    String token = SecurityUtils.generateTokenForTesting(
      app.Id,
      applicant.id,
      ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE,
      ApplicationConstant.FLOW_TYPE_APPLICATION
    );

    //200
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new MockAPIResponse('AlloyKYC', '201'));
    ApexRequest request = new ApexRequest();
    request.token = token;
    ApexRequest.setApplicantId(applicant.Id);
    AlloyProvider.getInstance();
    ApexResponse res = ApplicantController.verifyKYC(request);
    Test.stopTest();
  }

  @isTest
  static void verifyKYCTestTwo() {
    makeApplicationConfiguration();
    Application__c app = TestData.createApplication();
    insert app;
    Applicant__c applicant = createApplicantDataWithChild(app);

    //200
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new MockAPIResponse('AlloyKYCFailed', '400'));
    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    ApexResponse res = ApplicantController.verifyKYC(request);
    Test.stopTest();
  }

  @isTest
  static void validateExistingCustomerTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);
    String token = SecurityUtils.generateTokenForTesting(
      application.Id,
      applicant.id,
      ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE,
      ApplicationConstant.FLOW_TYPE_APPLICATION
    );

    //200
    ApexRequest request = new ApexRequest();
    request.token = token;
    ApexResponse res = ApplicantController.validateExistingCustomer(request);
    // system.assertEquals(200, res.status, 'success');

    createExistingContact(applicant.SSN__c);
    request = new ApexRequest();
    request.token = token;
    res = ApplicantController.validateExistingCustomer(request);
  }
  @isTest
  static void getBaseURLTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = createApplicantDataWithChild(application);

    //200
    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    ApexResponse res = ApplicantController.getBaseURL(request);
    // system.assertEquals(200, res.status, 'success');
  }
}