force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/ApplicantType__c.field-meta.xml
<CustomField>
    <fullName>ApplicantType__c</fullName>
    <description>Describes applicant type primary or joint</description>
    <label>Applicant Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Joint</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Emergency Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/test/default/classes/ApexRequestTest.cls
@istest
public with sharing class ApexRequestTest {
  private static Account makeAccountData() {
    Account acc = TestData.createAccount();
    acc = (Account) DatabaseUtils.insertRecord(acc);
    return acc;
  }
  private static Applicant__c makeApplicantData() {
    Account acc = TestData.createAccount();
    acc = (Account) DatabaseUtils.insertRecords(new List<Account>{ acc })[0];
    Applicant__c applicant = TestData.createApplicant(acc.Id);
    applicant.Email__c = 'test@mail.com';
    applicant = (Applicant__c) DatabaseUtils.insertRecord(applicant);
    return applicant;
  }
  @istest
  static void apexRequestTestOne() {
    Account acc = makeAccountData();
    Applicant__c applicant = makeApplicantData();
    ApexRequest request = new ApexRequest();
    test.startTest();
    request.setData(acc);
    request.setHeader('header');
    request.setData('Data');
    request.setHeader(new Map<String, Object>{ 'Account' => acc });
    ApexRequest.setApplicationName(acc.Name);
    ApexRequest.setApplicantId(applicant.Id);
    ApexRequest.setApplicantType(applicant.ApplicantType__c);
    ApexRequest.setFlowType('GetStarted');
    ApexRequest.setToken('Token');
    request.setRequest();
    ApexRequest.setApplicationId(acc.Id);
    id appid = ApexRequest.getApplicationId();
    ApexRequest.getRequest();
    ApexRequest.getParams();
    ApexRequest.getParams('Account');
    ApexRequest.getApplicationName();
    ApexRequest.getApplicantId();
    ApexRequest.getApplicantType();
    ApexRequest.getToken();
    ApexRequest.getFlowType();
    test.stopTest();
    system.assertEquals(acc.Id, appid, 'success');
  }
}