force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/ApplicantType__c.field-meta.xml
<CustomField>
    <fullName>ApplicantType__c</fullName>
    <description>Describes applicant type primary or joint</description>
    <label>Applicant Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Joint</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Emergency Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/EmailOtp__c.field-meta.xml
<CustomField>
    <fullName>EmailOtp__c</fullName>
    <description>To store Email Otp</description>
    <label>Email Otp</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First Name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Customer last name</description>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/OTPExpireTime__c.field-meta.xml
<CustomField>
    <fullName>OTPExpireTime__c</fullName>
    <description>OTP expire time</description>
    <inlineHelpText>OTP expire time</inlineHelpText>
    <label>OTP Expire Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Applicant__c/recordTypes/Primary.recordType-meta.xml
<RecordType>
    <fullName>Primary</fullName>
    <active>true</active>
    <description>Primary Applicant</description>
    <label>Primary</label>
</RecordType>

force-app/main/default/objects/ApplicationConfiguration__c/ApplicationConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Configuration</label>
</CustomObject>

force-app/main/default/objects/ApplicationConfiguration__c/fields/OTPExpirationTime__c.field-meta.xml
<CustomField>
    <fullName>OTPExpirationTime__c</fullName>
    <description>OTP Expiration Time</description>
    <label>OTPExpirationTime</label>
    <type>Number</type>
    <scale>0</scale>
    <precision>4</precision>
</CustomField>

force-app/main/default/classes/CustomerEmailService.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Service
 * @author Digital Align Team
 * @reference
 * @description Contains email notification related customer
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global virtual with sharing class CustomerEmailService extends AbstractService {
  @TestVisible
  private static CustomerEmailService serviceInstance;

  public CustomerEmailService() {
    super(CustomerEmailService.class);
  }

  /**
   * @description Provides a singleton instance of CustomerEmailService from which all other class methods can be accessed.
   * @author Digital Align Team | 07-12-2021
   * @return Object  singleton
   **/
  public static CustomerEmailService getInstance() {
    if (serviceInstance == null) {
      serviceInstance = (CustomerEmailService) getInstance(
        CustomerEmailService.class
      );
    }
    return serviceInstance;
  }

  /**
   * @description Dispatch email notification to OTP to Applicant
   * @author Digital Align | 11-05-2021
   * @param Applicant__c applicant
   **/
  global virtual void sendEmailOTP(Applicant__c applicant) {
    String expireTime = string.valueOf(
      (Integer) ApplicationConfiguration__c.getOrgDefaults()
        .OTPExpirationTime__c
    );
    //applicant.OTPExpireTime__c.format('MM/dd/yyyy HH:mm:ss')
    EmailNotificationBuilder.newInstance('OTPVerificationEmail', applicant.Id)
      .setToAddresses(applicant.Email__c)
      .setSubstitute(
        new Map<String, String>{
          '{FirstName}' => applicant.FirstName__c,
          '{LastName}' => applicant.LastName__c,
          '{OTP}' => applicant.EmailOtp__c,
          '{ExpireTime}' => expireTime
        }
      );
    List<Messaging.SendEmailResult> result = EmailNotificationBuilder.sendEmail();
    if (!CollectionUtils.isListEmpty(result)) {
      if (result[0].success) {
        log?.debug('Email sent Successfully');
      } else {
        log?.debug('Failed to send Email ');
        throw new customException('email not sent');
      }
    }
  }

  /**
   * @description Notification to family member on reference
   * @author Digital Align Team | 11-10-2021
   * @param List<Applicant__c> applicants
   **/
  global virtual void notifyFamilyMember(List<Applicant__c> applicants) {
    Applicant__c primaryApplicant;

    for (Applicant__c applicant : applicants) {
      Set<String> applicantTypes = new Set<String>(
        applicant.ApplicantType__c.split(';')
      );
      if (applicantTypes.contains('Primary')) {
        primaryApplicant = applicant;
      }
    }

    for (Applicant__c applicant : applicants) {
      Set<String> applicantTypes = new Set<String>(
        applicant.ApplicantType__c.split(';')
      );
      if (applicantTypes.contains('Family Member')) {
        EmailNotificationBuilder.newInstance(
            'NotificationToFamilyMember',
            applicant.Id
          )
          .setToAddresses(applicant.Email__c)
          .setCcAddresses(primaryApplicant.Email__c)
          .setSubstitute(
            new Map<String, String>{
              '{primaryFirstName}' => primaryApplicant.FirstName__c,
              '{primaryLastName}' => primaryApplicant.LastName__c,
              '{productName}' => 'Membership Account',
              '{applicationNumber}' => 'APP-001'
            }
          );
      }
    }

    List<Messaging.SendEmailResult> result = EmailNotificationBuilder.sendEmail();
    if (!CollectionUtils.isListEmpty(result)) {
      if (result[0].success) {
        log?.debug('Email sent Successfully');
      } else {
        log?.debug('Failed to send Email ');
        throw new customException('email not sent');
      }
    }
  }
}