force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/SObjectConstructorTest.cls
@istest
public with sharing class SObjectConstructorTest {
  private static Application__c makeAccountData() {
    Application__c acc = TestData.createAccount();
    acc = (Application__c) DatabaseUtils.insertRecord(acc);
    return acc;
  }

  private static Applicant__c makeApplicantData() {
    Application__c acc = TestData.createAccount();
    acc = (Application__c) DatabaseUtils.insertRecords(
      new List<Application__c>{ acc }
    )[0];
    Applicant__c applicant = TestData.createApplicant(acc.Id);
    applicant.Email__c = 'test@mail.com';
    applicant = (Applicant__c) DatabaseUtils.insertRecord(applicant);
    return applicant;
  }
  @istest
  static void SObjectConstructorTestOne() {
    Application__c acc = TestData.createAccount();
    Applicant__c applicant = makeApplicantData();
    test.startTest();
    SObjectConstructor sObj = new SObjectConstructor();
    SObjectConstructor.getInstance(acc)
      .setChildObjects('relationShipName', new List<SObject>{ applicant })
      .setChildObject('relationShipName', applicant)
      .addChildObjects('relationShipName', new List<SObject>{ applicant })
      .addChildObject('relationShipName', applicant)
      .setLookupObject('relationShipName', applicant)
      .build();
    SObjectConstructor.deserialize(
      SObjectConstructor.serialize(acc),
      Application__c.class
    );
    SObjectConstructor.writeFieldsAsList(new List<SObject>{ applicant });

    test.stopTest();
  }
}