force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/recordTypes/Primary.recordType-meta.xml
<RecordType>
    <fullName>Primary</fullName>
    <active>true</active>
    <description>Primary Applicant</description>
    <label>Primary</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/FinancialAccount__c.object-meta.xml
<CustomObject>
    <description
  >A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Financial Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DAT-200</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>related product</description>
    <label>Financial Product</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/recordTypes/Checking.recordType-meta.xml
<RecordType>
    <fullName>Checking</fullName>
    <active>true</active>
    <description>Checking Financial Account</description>
    <label>Checking</label>
</RecordType>

force-app/main/default/objects/FinancialAccount__c/recordTypes/Savings.recordType-meta.xml
<RecordType>
    <fullName>Savings</fullName>
    <active>true</active>
    <description>Saving Financial Account</description>
    <label>Savings</label>
</RecordType>

force-app/main/default/objects/FinancialAccountTransaction__c/FinancialAccountTransaction__c.object-meta.xml
<CustomObject>
    <description
  >Represents information about financial account transactions.</description>
    <label>Financial Account Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccountTransaction__c/fields/FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Financial Account</description>
    <label>Financial Account</label>
    <referenceTo>FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Transactions</relationshipLabel>
    <relationshipName>FinancialAccountTranslations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialProduct__c/FinancialProduct__c.object-meta.xml
<CustomObject>
    <description>Object to store all product related data</description>
    <label>Financial Product</label>
    <nameField>
        <label>FinancialProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>Object to capture dealer onboarding questions</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Survey related to financial account</description>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/SurveyQuestion__c.field-meta.xml
<CustomField>
    <fullName>SurveyQuestion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SurveyTemplate Item</label>
    <referenceTo>SurveyQuestion__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyQuestion__c/SurveyQuestion__c.object-meta.xml
<CustomObject>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyQuestion__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Question</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Questions</relationshipLabel>
    <relationshipName>SurveyQuestions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/SurveyTemplate__c.object-meta.xml
<CustomObject>
    <label>SurveyTemplate</label>
    <nameField>
        <label>SurveyTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SurveyTemplate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplate__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Financial Product Linked</description>
    <label>FinancialProduct</label>
    <referenceTo>FinancialProduct__c</referenceTo>
    <relationshipLabel>Survey Templates</relationshipLabel>
    <relationshipName>SurveyTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/test/default/classes/SurveyResolverTest.cls
@istest
public with sharing class SurveyResolverTest {
  private static Application__c makeApplicationData() {
    Application__c acc = TestData.createApplication();
    acc = (Application__c) DatabaseUtils.insertRecord(acc);

    List<FinancialProduct__c> products = TestData.createProduct();
    products = (List<FinancialProduct__c>) DatabaseUtils.insertRecords(products);

    FinancialAccount__c finAcc = TestData.makeFinancialAccount();
    finAcc.mflow__FinancialProduct__c = products[0].Id;
    finAcc.mflow__Application__c = acc.Id;
    Id recType = Schema.SObjectType.FinancialAccount__c.getRecordTypeInfosByName().get('Savings').getRecordTypeId();
    finAcc.RecordTypeId = recType;
    finAcc = (FinancialAccount__c) DatabaseUtils.insertRecord(finAcc);

    FinancialAccountTransaction__c tran = TestData.createFinancialAccountTransaction();
    tran.FinancialAccount__c = finAcc.Id;
    tran.TransactionDate__c = DateTime.newInstance(2007, 6, 23, 3, 3, 3);
    tran = (FinancialAccountTransaction__c) DatabaseUtils.insertRecord(tran);

    Applicant__c applicant = TestData.createApplicant('Primary');
    applicant.Application__c = acc.Id;
    applicant = (Applicant__c) DatabaseUtils.insertRecord(applicant);

    mflow__Consent__c consent = TestData.createConsent();
    consent.Application__c = acc.Id;
    consent.mflow__Applicant__c = applicant.Id;
    consent = (mflow__Consent__c) DatabaseUtils.insertRecord(consent);

    acc.Applicants__r.addAll(new List<Applicant__c>{ applicant });
    acc.mflow__FinancialAccounts__r.addAll(new List<FinancialAccount__c>{ finAcc });
    return acc;
  }
  private static mflow__SurveyTemplate__c makeSurveyTemplate() {
    mflow__SurveyTemplate__c surveyTemplate = TestData.createSurveyTemplates();
    surveyTemplate = (mflow__SurveyTemplate__c) DatabaseUtils.insertRecord(surveyTemplate);

    SurveyQuestion__c surveyQuestion = TestData.createSurveyQuestion();
    surveyQuestion.mflow__SurveyTemplate__c = surveyTemplate.Id;
    surveyQuestion = (SurveyQuestion__c) DatabaseUtils.insertRecord(surveyQuestion);
    surveyTemplate.SurveyQuestions__r.addALl(new List<SurveyQuestion__c>{ surveyQuestion });
    return surveyTemplate;
  }
  @IsTest
  private static void fetchSurveyTest() {
    mflow__Application__c application = makeApplicationData();
    mflow__SurveyTemplate__c surveyTemplate = makeSurveyTemplate();
    List<Applicant__c> applicant = [SELECT id FROM Applicant__c WHERE mflow__Application__c = :application.Id];
    ApexRequest request = new ApexRequest();
    request.header = '{"eventIdentifier":"CustomerFlowQuestionaire","filter":[]}';
    ApexRequest.setApplicationId(application.Id);
    ApexRequest.setApplicantId(applicant[0].Id);
    test.startTest();
    ApplicationController.fetchSurvey(request);
    SurveyResolver.getInstance()
      .resolveSurveys(
        application,
        new List<object>{ new Map<String, Object>{ 'Name' => 'Checking Application__c Agreement' } }
      );
    SurveyResolver.getInstance().resolveSurveys(application);
    SurveyResolver.getInstance().resolveSurveys(application, new List<object>());
    SurveyResolver.getInstance().removeDuplicateSurveys(new List<Survey__c>());
    SurveyResolver.getInstance().sort(new List<Survey__c>());
    SurveyResolver.getInstance()
      .buildSurvey(new List<SurveyTemplate__c>{ TestData.createSurveyTemplates() }, application.Id);

    test.stopTest();
  }
}