force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/ApplicantType__c.field-meta.xml
<CustomField>
    <fullName>ApplicantType__c</fullName>
    <description>Describes applicant type primary or joint</description>
    <label>Applicant Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Joint</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Emergency Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SessionExpireTime__c.field-meta.xml
<CustomField>
    <fullName>SessionExpireTime__c</fullName>
    <description>Session Expire Time</description>
    <inlineHelpText>OTP expire time</inlineHelpText>
    <label>Session Expire Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Application submission status by applicant</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Application submission status by applicant</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Abandoned</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Review In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Submit for Review</fullName>
    </customValue>
    <customValue>
        <fullName>Saved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Funding in Progress</fullName>
    </customValue>
    <description>Status of application and applicants</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchToAbandonedApplication.cls
/**
 * Copyright (c) 2022 Digital Align
 * @group BatchJob
 * @author Digital Align Team
 * @reference
 * @description
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global class BatchToAbandonedApplication implements Database.batchable<sObject> {
  private Logger log = Logger.getInstance(BatchToAbandonedApplication.class);
  /**
   * @description
   * @author Digital Align Team | 04-26-2022
   * @param Database.BatchableContext bc
   * @return Database.QueryLocator
   **/
  global Database.QueryLocator start(Database.BatchableContext bc) {
    log?.debug('Start BatchToAbandonedApplication ');

    String qry = Query.newInstance(Application__c.SObjectType)
      .addFields()
      .queryChild('mflow__Applicants__r')
      .addFields()
      .addFields('RecordType.Name')
      .grpOpen()
      .whereEq('Status__c', ApplicationConstant.IN_PROGRESS)
      .orCon()
      .whereEq('Status__c', ApplicationConstant.DRAFT)
      .grpClose()
      .andCon()
      .whereLte('LastModifiedDate', DateTime.now().addMinutes(-60))
      .andCon()
      .whereLte('SessionExpireTime__c', DateTime.now())
      .andCon()
      .whereCon('CreatedDate >= LAST_N_DAYS:90')
      .run()
      .whereIn(
        'Id',
        Query.newInstance(mflow__Applicant__c.SObjectType)
          .addFields('Application__c')
          .grpOpen()
          .whereEq('Status__c', ApplicationConstant.IN_PROGRESS)
          .orCon()
          .whereEq('Status__c', ApplicationConstant.DRAFT)
          .grpClose()
          .andCon()
          .whereLte('LastModifiedDate', DateTime.now().addMinutes(-60))
          .andCon()
          .whereLte('SessionExpireTime__c', DateTime.now())
          .andCon()
          .whereCon('CreatedDate >= LAST_N_DAYS:90')
          .andCon()
          .grpOpen()
          .whereEq('Application__r.Status__c', ApplicationConstant.IN_PROGRESS)
          .orCon()
          .whereEq('Application__r.Status__c', ApplicationConstant.SAVED)
          .grpClose()
          .toString()
      )
      .addLimit(10000)
      .toString();
    log?.debug('qry :' + qry);
    return Database.getQueryLocator(qry);
  }

  /**
   * @description
   * @author Digital Align Team | 04-26-2022
   * @param Database.BatchableContext BC
   * @param List<Application__c> scope
   **/
  global void execute(Database.BatchableContext bc, List<Application__c> applications) {
    log?.debug('execute BatchToAbandonedApplication ');
    for (Application__c application : applications) {
      application.Status__c = ApplicationConstant.ABANDONED;
      ApexRequest.setApplicationId(application.Id);
      for (Applicant__c applicant : application.Applicants__r) {
        Map<String, String> params = new Map<String, String>();
        if (applicant.ApplicantType__c == ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE) {
          params.put('flw', 'ApplicationFlow');
          params.put('urlSuffix', '/other/resume/otp');
          params.put('aplType', ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE);
        } else {
          params.put('flw', 'JointFlow');
          params.put('urlSuffix', '/other/resume/otp');
          params.put('aplType', ApplicationConstant.APPLICANT_JOINT_RECORDTYPE);
        }
        params.put('aplId', applicant.Id);
        params.put('ch', 'Virtual');
        EmailNotificationBuilder.newInstance('ResumeApplicationEmail', applicant.Id)
          .setToAddresses(applicant.Email__c)
          .setSubstitute(new Map<String, String>{ '{url}' => CustomerEmailService.getInstance().generateUrl(params) });
      }
    }
    CustomerEmailService.getInstance().sendEmail();
    upsert applications;
    Logger.persist();
  }

  /**
   * @description
   * @author Digital Align Team | 04-26-2022
   * @param Database.BatchableContext BC
   **/
  global void finish(Database.BatchableContext bc) {
    log?.debug('Finished BatchToAbandonedApplication ');
  }
}