force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <description>Applicant date of birth</description>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First Name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IsExistingCustomer__c.field-meta.xml
<CustomField>
    <fullName>IsExistingCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsExistingCustomer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Customer last name</description>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>SSN number</description>
    <label>SSN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/recordTypes/Primary.recordType-meta.xml
<RecordType>
    <fullName>Primary</fullName>
    <active>true</active>
    <description>Primary Applicant</description>
    <label>Primary</label>
</RecordType>

force-app/main/default/objects/ContactPointAddress/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and contact point address</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Contact Point Addresses</relationshipLabel>
    <relationshipName>ContactPointAddresses</relationshipName>
    <type>Lookup</type>
</CustomField>

fsc-app/main/default/objects/FinServ__IdentificationDocument__c/FinServ__IdentificationDocument__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__IdentificationDocumentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about documents used to verify a person&apos;s identity.</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>DOC-{000000000}</displayFormat>
        <label>Document</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IdentificationDocument__c/IdentificationDocument__c.object-meta.xml
<CustomObject>
    <description>Identification Document for Applicants</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IdentificationDocument__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Identity Document Number</description>
    <label>Document Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IdentificationDocument__c/fields/IssuedStateCode__c.field-meta.xml
<CustomField>
    <fullName>IssuedStateCode__c</fullName>
    <description>Two letter abbreviation of state field</description>
    <label>Issued State Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Alloy/AlloyServiceHelper.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Service
 * @author Digital Align Team
 * @reference
 * @description Application service
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global virtual with sharing class AlloyServiceHelper extends AbstractService {
  @TestVisible
  private static AlloyServiceHelper serviceInstance;

  public AlloyServiceHelper() {
    super(AlloyServiceHelper.class);
  }

  /**
   * @description Provides a singleton instance of AlloyServiceHelper from which all other class methods can be accessed.
   * @author Digital Align Team | 03/31/2022
   * @return Object  singleton
   **/
  public static AlloyServiceHelper getInstance() {
    if (serviceInstance == null) {
      serviceInstance = (AlloyServiceHelper) getInstance(AlloyServiceHelper.class);
    }
    return serviceInstance;
  }

  public String buildIDVRequest(Applicant__c applicant) {
    AlloyDTO.IDVRequest idvDTO = new AlloyDTO.IDVRequest();
    Boolean isJointApplicant;
    mflow__IdentificationDocument__c identificationObj = applicant.mflow__IdentificationDocuments__r.isEmpty()
      ? new mflow__IdentificationDocument__c()
      : applicant.mflow__IdentificationDocuments__r[0];

    ContactPointAddress addresses = applicant.mflow__ContactPointAddresses__r.isEmpty()
      ? new ContactPointAddress()
      : applicant.mflow__ContactPointAddresses__r[0];

    for (ContactPointAddress add : applicant.mflow__ContactPointAddresses__r) {
      if (add.AddressType.equalsignorecase('Primary')) {
        addresses = add;
      }
    }
    idvDTO.name_first = applicant.FirstName__c;
    idvDTO.name_last = applicant.LastName__c;
    idvDTO.document_ssn = applicant.SSN__c;
    idvDTO.birth_date =
      applicant.BirthDate__c.year() +
      '-' +
      String.valueOf(applicant.BirthDate__c.month()).leftpad(2, '0') +
      '-' +
      String.valueOf(applicant.BirthDate__c.day()).leftpad(2, '0');
    idvDTO.phone_number = applicant.Phone__c;
    idvDTO.email_address = applicant.Email__c;

    //mapiing of address
    idvDTO.address_line_1 = addresses.Street;
    idvDTO.address_city = addresses.City;
    idvDTO.address_state = identificationObj.IssuedStateCode__c;
    idvDTO.address_postal_code = addresses.PostalCode;
    idvDTO.address_country_code = 'US';

    isJointApplicant = applicant.mflow__ApplicantType__c.equalsignorecase('Primary') ? false : true;
    idvDTO.ip_address_v4 = ApplicationServiceHelper.getinstance().getIpAddress();
    idvDTO.document_license = identificationObj.DocumentNumber__c;
    idvDTO.document_license_state = identificationObj.IssuedStateCode__c;
    idvDTO.meta = new AlloyDTO.Meta(applicant.IsExistingCustomer__c, isJointApplicant);

    return AlloyDTO.generateRequest(idvDTO);
  }
}