force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/ApplicantType__c.field-meta.xml
<CustomField>
    <fullName>ApplicantType__c</fullName>
    <description>Describes applicant type primary or joint</description>
    <label>Applicant Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Joint</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Emergency Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Application submission status by applicant</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/recordTypes/Joint.recordType-meta.xml
<RecordType>
    <fullName>Joint</fullName>
    <active>true</active>
    <description>Joint Applicant</description>
    <label>Joint</label>
</RecordType>

force-app/main/default/objects/Applicant__c/recordTypes/Primary.recordType-meta.xml
<RecordType>
    <fullName>Primary</fullName>
    <active>true</active>
    <description>Primary Applicant</description>
    <label>Primary</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Application submission status by applicant</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentRequest__c/DocumentRequest__c.object-meta.xml
<CustomObject>
    <description>Document Request for an application</description>
    <label>Document Request</label>
    <nameField>
        <displayFormat>Doc{0000}</displayFormat>
        <label>Document Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentRequest__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked Applicant</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Document Requests</relationshipLabel>
    <relationshipName>DocumentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentRequest__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Document Requests</relationshipLabel>
    <relationshipName>DocumentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/FinancialAccount__c.object-meta.xml
<CustomObject>
    <description
  >A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Financial Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialAccount__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DAT-200</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>FinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialAccount__c/recordTypes/Savings.recordType-meta.xml
<RecordType>
    <fullName>Savings</fullName>
    <active>true</active>
    <description>Saving Financial Account</description>
    <label>Savings</label>
</RecordType>

force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Abandoned</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Review In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Submit for Review</fullName>
    </customValue>
    <customValue>
        <fullName>Saved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Funding in Progress</fullName>
    </customValue>
    <description>Status of application and applicants</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerPortalService.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Service
 * @author Digital Align Team
 * @reference
 * @description Application service
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global virtual with sharing class CustomerPortalService extends AbstractService {
  @TestVisible
  private static CustomerPortalService serviceInstance;

  public CustomerPortalService() {
    super(CustomerPortalService.class);
  }

  /**
   * @description Provides a singleton instance of CustomerPortalService from which all other class methods can be accessed.
   * @author Digital Align Team | 02/11/2022
   * @return Object  singleton
   **/
  public static CustomerPortalService getInstance() {
    if (serviceInstance == null) {
      serviceInstance = (CustomerPortalService) getInstance(CustomerPortalService.class);
    }
    return serviceInstance;
  }
  /**
   * @description
   * @author Digital Align Team | 02-14-2022
   * @param map<string object> params
   * @return List<Application__c>
   **/
  global virtual List<Application__c> authorize(map<string, object> params) {
    Applicant__c applicant = (Applicant__c) JSON.deserialize(
      JSON.serialize(params.get('applicant')),
      Applicant__c.class
    );
    List<Application__c> applications = CustomerPortalRepository.fetchApplicationByApplicantDetails(
      applicant.mflow__LastFourDigitsofSSN__c,
      applicant.mflow__Email__c,
      applicant.mflow__LastName__c
    );
    log?.debug('Applications =' + applications);
    return applications;
  }

  /**
   * @description Fetch application by logged in applicant used for cusotmer portal
   * @author Digital Align Team | 06-09-2022
   * @return List<Application__c>
   **/
  global virtual List<Application__c> fetchMyApplication() {
    Applicant__c applicant = ApplicantRepository.fetchSession(ApexRequest.getSessionId())?.mflow__Applicant__r;
    return CustomerPortalRepository.readMyApplication(applicant);
  }

  /**
   * @description read application with child record used for customer portal
   * @author Digital Align Team | 06-10-2022
   * @return Application__c
   **/
  global virtual Application__c readApplicationWithChild(Map<String, Object> params) {
    Id applicationId = (Id) params.get('applicationId');
    Application__c application = CustomerPortalRepository.readApplicationWithChild(applicationId);
    List<Applicant__c> applicants = CustomerPortalRepository.readApplicantsWithChild(
      new Map<Id, SObject>(application.Applicants__r).keySet()
    );
    List<FinancialAccount__c> financialAccounts = CustomerPortalRepository.readFinancialAccountsWithChild(
      new Map<Id, SObject>(application.mflow__FinancialAccounts__r).keySet()
    );
    //Combine result into single application object
    SObjectConstructor builder = SObjectConstructor.getInstance(application);
    builder.setChildObjects('mflow__Applicants__r', applicants);
    builder.setChildObjects('mflow__FinancialAccounts__r', financialAccounts);
    return (Application__c) builder.build();
  }

  /**
   * @description resume application for customer portal , After login into portal customer get option to resume the application
   * Resume Type can be 'Email' or 'Url'
   * When applicantId is Empty, Primary applicant is fetched using application ID,
   * Otherwise Based on the applicant Id Email or Url will generated
   * @author Digital Align Team | 06-16-2022
   * @param Map<String Object> params
   * @return Object
   **/
  global virtual Object resumeApplication(Map<String, Object> params) {
    Id applicationId = (Id) params.get('applicationId');
    Id applicantId = (Id) params.get('applicantId');
    String resumeType = (String) params.get('resumeType');
    Applicant__c applicant;
    if (String.isNotBlank(applicationId) && String.isBlank(applicantId)) {
      applicant = CustomerPortalRepository.readPrimaryApplicant(applicationId);
    } else if (String.isNotBlank(applicationId) && String.isNotBlank(applicantId)) {
      applicant = CustomerPortalRepository.readApplicantById(applicationId, applicantId);
    }

    if (applicant == null) {
      throw new CustomException(System.Label.Applicant_ApplicantNotFound);
    }

    if (resumeType == 'Url') {
      Map<String, String> paramsEncrypt = new Map<String, String>();
      if (applicant.ApplicantType__c == ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE) {
        paramsEncrypt.put('flw', 'ApplicationFlow');
        paramsEncrypt.put('urlSuffix', '/savings/main-app/otp');
        paramsEncrypt.put('aplType', ApplicationConstant.APPLICANT_PRIMARY_RECORDTYPE);
      } else {
        paramsEncrypt.put('flw', 'JointFlow');
        paramsEncrypt.put('urlSuffix', '/savings/joint-app/otp');
        paramsEncrypt.put('aplType', ApplicationConstant.APPLICANT_JOINT_RECORDTYPE);
      }
      paramsEncrypt.put('appId', applicant.application__c);
      paramsEncrypt.put('aplId', applicant.Id);
      paramsEncrypt.put('ch', 'Virtual');
      return CustomerEmailService.getInstance().generateUrl(paramsEncrypt);
    } else if (resumeType == 'Email') {
      CustomerEmailService.getInstance().resumeApplication(applicant);
      return 'Email Sent Successfully';
    }
    return null;
  }

  /**
   * @description
   * @author Digital Align Team | 06-21-2022
   * @param ApexRequest request
   * @return virtual
   **/
  global virtual ContentVersion uploadDocument(ApexRequest request) {
    FileDTO dto = new FileDTO(
      (String) ApexRequest.getParams('title'),
      EncodingUtil.base64Decode((String) JSON.deserialize(request.data, String.class)),
      (Id) ApexRequest.getParams('parentID'),
      (String) ApexRequest.getParams('fileType'),
      (String) ApexRequest.getParams('fileSubType')
    );
    if (ApexRequest.getParams('shareType') != null) {
      dto.shareType = FileDTO.FileShareType.valueOf((String) ApexRequest.getParams('shareType'));
    }
    if (ApexRequest.getParams('visibility') != null) {
      dto.visibility = FileDTO.FileVisibility.valueOf((String) ApexRequest.getParams('visibility'));
    }
    ContentVersion cv = FileService.getInstance().createFile(dto);

    // Change status of the document Request after upload the document
    String parentId = (Id) ApexRequest.getParams('parentID');
    DocumentRequest__c docReq = new DocumentRequest__c(id = parentId, Status__c = 'Review');
    CustomerPortalRepository.upsertRecord(docReq);
    return cv;
  }
}