force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/EmailOtp__c.field-meta.xml
<CustomField>
    <fullName>EmailOtp__c</fullName>
    <description>To store Email Otp</description>
    <label>Email Otp</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IsEmailVerified__c.field-meta.xml
<CustomField>
    <fullName>IsEmailVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if customer email is verified</description>
    <label>Is Email Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Customer last name</description>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SessionToken__c.field-meta.xml
<CustomField>
    <fullName>SessionToken__c</fullName>
    <description>SessionToken</description>
    <label>Session Token</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>SSN number</description>
    <label>SSN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/SessionToken__c.field-meta.xml
<CustomField>
    <fullName>SessionToken__c</fullName>
    <description>SessionToken</description>
    <label>Session Token</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationConfiguration__c/ApplicationConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Configuration</label>
</CustomObject>

force-app/main/default/objects/DocumentRequest__c/DocumentRequest__c.object-meta.xml
<CustomObject>
    <description>Document Request for an application</description>
    <label>Document Request</label>
    <nameField>
        <displayFormat>Doc{0000}</displayFormat>
        <label>Document Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentRequest__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked Applicant</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Document Requests</relationshipLabel>
    <relationshipName>DocumentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentRequest__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Document Requests</relationshipLabel>
    <relationshipName>DocumentRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialProduct__c/FinancialProduct__c.object-meta.xml
<CustomObject>
    <description>Object to store all product related data</description>
    <label>Financial Product</label>
    <nameField>
        <label>FinancialProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SessionManagement__c/SessionManagement__c.object-meta.xml
<CustomObject>
    <label>Session Management</label>
    <nameField>
        <displayFormat>S{0000000}</displayFormat>
        <label>Session Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SessionManagement__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Session Managements</relationshipLabel>
    <relationshipName>SessionManagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SessionManagement__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Session Managements</relationshipLabel>
    <relationshipName>SessionManagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SessionManagement__c/fields/EmailOtp__c.field-meta.xml
<CustomField>
    <fullName>EmailOtp__c</fullName>
    <label>Email Otp</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SessionManagement__c/fields/SessionToken__c.field-meta.xml
<CustomField>
    <fullName>SessionToken__c</fullName>
    <description>Session Token</description>
    <label>Session Token</label>
    <type>TextArea</type>
</CustomField>

force-app/test/default/classes/OnlinePortalControllerTest.cls
@istest
public with sharing class OnlinePortalControllerTest {
  //makeApplicationConfiguration
  private static void makeApplicationConfiguration() {
    ApplicationConfiguration__c appConfig = TestData.createApplicationConfiguration();
    insert appConfig;
    TestData.createSiteSetting();
    List<FinancialProduct__c> products = TestData.createProduct();
    insert products;
  }

  @isTest
  static void productSelectorTest() {
    makeApplicationConfiguration();
    //200
    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    ApexResponse res = OnlinePortalController.productSelector(request);
    system.assertEquals(200, res.status, 'success');

    request = new ApexRequest();
    request.token = 'InvalidToken';
    res = OnlinePortalController.productSelector(null);
    system.assertEquals(400, res.status, 'success');
  }

  @isTest
  static void onlinePortalAuthenticateTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = Application.Applicants__r[0];
    applicant.Email__c = 'test@test.com';
    applicant.Phone__c = '9876543210';
    applicant.LastName__c = 'lastname';
    applicant.SSN__c = '9876543210';
    applicant.IsEmailVerified__c = true;
    update applicant;

    // Failure
    ApexRequest request = new ApexRequest();
    request.setHeader(
      new Map<String, object>{ 'lastName' => 'Failure', 'email' => applicant.Email__c, 'ssn' => applicant.SSN__c }
    );
    ApexResponse res = OnlinePortalController.onlinePortalAuthenticate(request);

    //Success case
    request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setHeader(
      new Map<String, object>{
        'lastName' => applicant.LastName__c,
        'email' => applicant.Email__c,
        'ssn' => applicant.SSN__c
      }
    );
    res = OnlinePortalController.onlinePortalAuthenticate(request);
    system.assertEquals(200, res.status, 'success');
  }

  @isTest
  static void onlinePortalAuthorizeTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = Application.Applicants__r[0];
    applicant.Email__c = 'test@test.com';
    applicant.Phone__c = '9876543210';
    applicant.LastName__c = 'lastname';
    applicant.SSN__c = '9876543210';
    applicant.IsEmailVerified__c = true;
    update applicant;

    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setHeader(
      new Map<String, object>{
        'lastName' => applicant.LastName__c,
        'email' => applicant.Email__c,
        'ssn' => applicant.SSN__c
      }
    );

    ApexResponse res = OnlinePortalController.onlinePortalAuthenticate(request);

    SessionManagement__c sn = (SessionManagement__c) (JSON.deserialize((String) res.data, SessionManagement__c.class));

    //Failure no EMail OTP
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'sessionId' => sn.Id });
    res = OnlinePortalController.onlinePortalAuthorize(request);

    sn = [SELECT EmailOtp__c FROM SessionManagement__c WHERE id = :sn.Id];
    system.debug('sn :' + sn);

    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'sessionId' => sn.Id, 'email' => sn.EmailOtp__c });
    res = OnlinePortalController.onlinePortalAuthorize(request);
    system.assertEquals(200, res.status, 'success');
  }

  @isTest
  static void fetchMyApplicationTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = Application.Applicants__r[0];
    applicant.Email__c = 'test@test.com';
    applicant.Phone__c = '9876543210';
    applicant.LastName__c = 'lastname';
    applicant.SSN__c = '9876543210';
    applicant.IsEmailVerified__c = true;
    update applicant;

    //onlinePortalAuthenticate
    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setHeader(
      new Map<String, object>{
        'lastName' => applicant.LastName__c,
        'email' => applicant.Email__c,
        'ssn' => applicant.SSN__c
      }
    );

    ApexResponse res = OnlinePortalController.onlinePortalAuthenticate(request);
    SessionManagement__c sn = (SessionManagement__c) (JSON.deserialize((String) res.data, SessionManagement__c.class));
    sn = [SELECT EmailOtp__c FROM SessionManagement__c WHERE id = :sn.Id];
    system.debug('sn :' + sn);

    //onlinePortalAuthorize
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'sessionId' => sn.Id, 'email' => sn.EmailOtp__c });
    res = OnlinePortalController.onlinePortalAuthorize(request);
    system.assertEquals(200, res.status, 'success');

    //readApplicationWithChild Sucess
    sn = (SessionManagement__c) (JSON.deserialize((String) res.data, SessionManagement__c.class));

    request = new ApexRequest();
    request.token = sn.SessionToken__c;
    res = OnlinePortalController.fetchMyApplication(request);
    system.assertEquals(200, res.status, 'success');

    //readApplicationWithChild Exception
    request = new ApexRequest();
    res = OnlinePortalController.fetchMyApplication(request);
    system.assertEquals(400, res.status, 'success');
  }

  @isTest
  static void readApplicationWithChildTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = Application.Applicants__r[0];
    applicant.Email__c = 'test@test.com';
    applicant.Phone__c = '9876543210';
    applicant.LastName__c = 'lastname';
    applicant.SSN__c = '9876543210';
    applicant.IsEmailVerified__c = true;
    update applicant;

    //onlinePortalAuthenticate
    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setHeader(
      new Map<String, object>{
        'lastName' => applicant.LastName__c,
        'email' => applicant.Email__c,
        'ssn' => applicant.SSN__c
      }
    );

    ApexResponse res = OnlinePortalController.onlinePortalAuthenticate(request);
    SessionManagement__c sn = (SessionManagement__c) (JSON.deserialize((String) res.data, SessionManagement__c.class));
    sn = [SELECT EmailOtp__c FROM SessionManagement__c WHERE id = :sn.Id];
    system.debug('sn :' + sn);

    //onlinePortalAuthorize
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'sessionId' => sn.Id, 'email' => sn.EmailOtp__c });
    res = OnlinePortalController.onlinePortalAuthorize(request);
    system.assertEquals(200, res.status, 'success');

    //readApplicationWithChild Sucess
    sn = (SessionManagement__c) (JSON.deserialize((String) res.data, SessionManagement__c.class));

    request = new ApexRequest();
    request.token = sn.SessionToken__c;
    request.setHeader(new Map<String, object>{ 'applicationId' => application.Id });
    res = OnlinePortalController.readApplicationWithChild(request);
    system.assertEquals(200, res.status, 'success');

    //readApplicationWithChild Exception
    request = new ApexRequest();
    res = OnlinePortalController.readApplicationWithChild(request);
    system.assertEquals(400, res.status, 'success');
  }

  @isTest
  static void resumeApplicationTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = Application.Applicants__r[0];
    applicant.Email__c = 'test@test.com';
    applicant.Phone__c = '9876543210';
    applicant.LastName__c = 'lastname';
    applicant.SSN__c = '9876543210';
    applicant.IsEmailVerified__c = true;
    update applicant;

    //onlinePortalAuthenticate
    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setHeader(
      new Map<String, object>{
        'lastName' => applicant.LastName__c,
        'email' => applicant.Email__c,
        'ssn' => applicant.SSN__c
      }
    );

    ApexResponse res = OnlinePortalController.onlinePortalAuthenticate(request);
    SessionManagement__c sn = (SessionManagement__c) (JSON.deserialize((String) res.data, SessionManagement__c.class));
    sn = [SELECT EmailOtp__c FROM SessionManagement__c WHERE id = :sn.Id];
    system.debug('sn :' + sn);

    //onlinePortalAuthorize
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'sessionId' => sn.Id, 'email' => sn.EmailOtp__c });
    res = OnlinePortalController.onlinePortalAuthorize(request);
    system.assertEquals(200, res.status, 'success');

    //Sucess
    sn = (SessionManagement__c) (JSON.deserialize((String) res.data, SessionManagement__c.class));

    request = new ApexRequest();
    request.token = sn.SessionToken__c;
    request.setHeader(new Map<String, object>{ 'applicationId' => application.Id, 'resumeType' => 'url' });
    res = OnlinePortalController.resumeApplication(request);
    system.assertEquals(200, res.status, 'success');

    request = new ApexRequest();
    request.token = sn.SessionToken__c;
    request.setHeader(new Map<String, object>{ 'applicationId' => application.Id, 'resumeType' => 'email' });
    res = OnlinePortalController.resumeApplication(request);
    system.assertEquals(200, res.status, 'success');

    request = new ApexRequest();
    request.token = sn.SessionToken__c;
    request.setHeader(new Map<String, object>{ 'applicationId' => application.Id });
    res = OnlinePortalController.resumeApplication(request);
    system.assertEquals(200, res.status, 'success');

    // Exception
    request = new ApexRequest();
    res = OnlinePortalController.resumeApplication(request);
    system.assertEquals(400, res.status, 'success');
  }

  @isTest
  static void uploadDocumentTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = Application.Applicants__r[0];
    applicant.Email__c = 'test@test.com';
    applicant.Phone__c = '9876543210';
    applicant.LastName__c = 'lastname';
    applicant.SSN__c = '9876543210';
    applicant.IsEmailVerified__c = true;
    update applicant;

    //test data
    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setHeader(
      new Map<String, object>{
        'lastName' => applicant.LastName__c,
        'email' => applicant.Email__c,
        'ssn' => applicant.SSN__c
      }
    );

    ApexResponse res = OnlinePortalController.onlinePortalAuthenticate(request);
    SessionManagement__c sn = (SessionManagement__c) (JSON.deserialize((String) res.data, SessionManagement__c.class));
    sn = [SELECT EmailOtp__c FROM SessionManagement__c WHERE id = :sn.Id];
    system.debug('sn :' + sn);

    //test data
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'sessionId' => sn.Id, 'email' => sn.EmailOtp__c });
    res = OnlinePortalController.onlinePortalAuthorize(request);
    system.assertEquals(200, res.status, 'success');

    //Sucess
    sn = (SessionManagement__c) (JSON.deserialize((String) res.data, SessionManagement__c.class));

    DocumentRequest__c docReq = new DocumentRequest__c();
    docReq.mflow__Applicant__c = applicant.id;
    docReq.mflow__Application__c = application.Id;
    docReq.mflow__Comments__c = 'Test';
    docReq.mflow__DocumentType__c = 'Address';
    docReq.mflow__Name__c = 'Test';
    docReq.mflow__Status__c = 'New';
    insert docReq;

    Map<String, String> header = new Map<String, String>();
    header.put('title', 'TestFile.txt');
    header.put('parentID', docReq.Id);
    header.put('fileType', 'Address');
    header.put('fileSubType', 'Other');
    header.put('shareType', 'I');
    header.put('visibility', 'AllUsers');

    request = new ApexRequest();
    request.token = sn.SessionToken__c;
    request.setHeader(header);
    request.setData(Json.serialize('data'));
    res = OnlinePortalController.uploadDocument(request);
    system.assertEquals(200, res.status, 'success');

    // Exception
    request = new ApexRequest();
    res = OnlinePortalController.uploadDocument(request);
    system.assertEquals(400, res.status, 'success');
  }

  @isTest
  static void fetchAllDocumentRequestFilesTest() {
    makeApplicationConfiguration();
    PageReference testPage = Page.error;
    Test.setCurrentPage(testPage);
    testPage.getParameters().put('pid', 'IC001');
    Application__c application = ApplicationService.getInstance().createApplication(new Map<String, String>());
    Applicant__c applicant = Application.Applicants__r[0];
    applicant.Email__c = 'test@test.com';
    applicant.Phone__c = '9876543210';
    applicant.LastName__c = 'lastname';
    applicant.SSN__c = '9876543210';
    applicant.IsEmailVerified__c = true;
    update applicant;

    //test data
    ApexRequest request = new ApexRequest();
    request.token = ApexRequest.getToken();
    request.setHeader(
      new Map<String, object>{
        'lastName' => applicant.LastName__c,
        'email' => applicant.Email__c,
        'ssn' => applicant.SSN__c
      }
    );

    ApexResponse res = OnlinePortalController.onlinePortalAuthenticate(request);
    SessionManagement__c sn = (SessionManagement__c) (JSON.deserialize((String) res.data, SessionManagement__c.class));
    sn = [SELECT EmailOtp__c FROM SessionManagement__c WHERE id = :sn.Id];
    system.debug('sn :' + sn);

    //test data
    request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'sessionId' => sn.Id, 'email' => sn.EmailOtp__c });
    res = OnlinePortalController.onlinePortalAuthorize(request);
    system.assertEquals(200, res.status, 'success');

    //Sucess
    sn = (SessionManagement__c) (JSON.deserialize((String) res.data, SessionManagement__c.class));

    DocumentRequest__c docReq = new DocumentRequest__c();
    docReq.mflow__Applicant__c = applicant.id;
    docReq.mflow__Application__c = application.Id;
    docReq.mflow__Comments__c = 'Test';
    docReq.mflow__DocumentType__c = 'Address';
    docReq.mflow__Name__c = 'Test';
    docReq.mflow__Status__c = 'New';
    insert docReq;

    Map<String, String> header = new Map<String, String>();
    header.put('title', 'TestFile.txt');
    header.put('parentID', docReq.Id);
    header.put('fileType', 'Address');
    header.put('fileSubType', 'Other');
    header.put('shareType', 'I');
    header.put('visibility', 'AllUsers');

    Test.enableChangeDataCapture();
    request = new ApexRequest();
    request.token = sn.SessionToken__c;
    request.setHeader(header);
    request.setData(Json.serialize('data'));
    res = OnlinePortalController.uploadDocument(request);
    system.assertEquals(200, res.status, 'success');

    Test.getEventBus().deliver();

    // success
    request = new ApexRequest();
    request.token = sn.SessionToken__c;
    request.setHeader(new Map<String, object>{ 'applicationId' => application.Id });
    res = OnlinePortalController.fetchAllDocumentRequestFiles(request);
    system.assertEquals(200, res.status, 'success');

    // Exception
    // request = new ApexRequest();
    // res = OnlinePortalController.fetchAllDocumentRequestFiles(request);
    // system.assertEquals(400, res.status, 'success');
  }
}