force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <description>Applicant date of birth</description>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>SSN number</description>
    <label>SSN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationConfiguration__c/ApplicationConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Configuration</label>
</CustomObject>

force-app/main/default/objects/ContactPointAddress/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and contact point address</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Contact Point Addresses</relationshipLabel>
    <relationshipName>ContactPointAddresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/test/default/classes/IdentityServiceTest.cls
@isTest
public with sharing class IdentityServiceTest {
  private static Account makeAccountData() {
    Account acc = TestData.createAccount();
    acc = (Account) DatabaseUtils.insertRecord(acc);
    return acc;
  }
  private static ContactPointAddress makeContactPointAddress(Id applicantId) {
    ContactPointAddress address = TestData.createContactPointAddress();
    address.Applicant__c = applicantId;
    address = (ContactPointAddress) DatabaseUtils.insertRecord(address);
    return address;
  }
  private static Applicant__c makeApplicantData() {
    Account acc = TestData.createAccount();
    acc = (Account) DatabaseUtils.insertRecords(new List<Account>{ acc })[0];
    Applicant__c applicant = TestData.createApplicant(acc.Id);
    applicant.Email__c = 'test@mail.com';
    applicant.SSN__c = '986584759';
    applicant.Phone__c = '7894661236';
    applicant.Birthdate__c = date.valueOf('1990-11-01');
    applicant = (Applicant__c) DatabaseUtils.insertRecord(applicant);
    return applicant;
  }
  private static ApplicationConfiguration__c makeApplicationConfiguration() {
    ApplicationConfiguration__c appConfig = TestData.createApplicationConfiguration();
    appConfig = (ApplicationConfiguration__c) DatabaseUtils.insertRecord(
      appConfig
    );
    return appConfig;
  }
  @isTest
  static void verifyCountyTestOne() {
    Account acc = makeAccountData();
    ApexRequest request = new ApexRequest();
    request.applicationId = acc.Id;
    request.setHeader(new Map<String, String>{ 'zipcode' => '98013' });
    Test.setMock(
      HttpCalloutMock.class,
      new IdentityServiceMock('GeocodingProvider', '200')
    );
    Test.startTest();
    ApexResponse response = IdentityController.verifyCounty(request);
    Test.stopTest();
    System.assertEquals(200, response.status, 'success');
  }
  @isTest
  static void verifyCountyTestTwo() {
    Account acc = makeAccountData();
    ApexRequest request = new ApexRequest();
    request.applicationId = acc.Id;
    Test.startTest();
    try {
      ApexResponse response1 = IdentityController.verifyCounty(request);
    } catch (Exception e) {
      System.assertEquals(e.getMessage(), 'Zipcode value not set');
    }
    Test.stopTest();
  }
  @isTest
  static void IdentityVerifyTestOne() {
    makeApplicationConfiguration();
    Applicant__c applicant = makeApplicantData();
    makeContactPointAddress(applicant.Id);
    ApexRequest request = new ApexRequest();
    request.applicationId = applicant.Application__c; //account ID
    request.setHeader(
      new Map<String, String>{
        'applicantId' => applicant.Id,
        'apiName' => 'SentiLink'
      }
    );
    Test.setMock(
      HttpCalloutMock.class,
      new IdentityServiceMock('SentiLinkProvider', '200')
    );
    Test.startTest();
    ApexResponse response = IdentityController.identityVerify(request);
    Test.stopTest();
  }
  @isTest
  static void IdentityVerifyTestTwo() {
    makeApplicationConfiguration();
    Applicant__c applicant = makeApplicantData();
    makeContactPointAddress(applicant.Id);
    ApexRequest request = new ApexRequest();
    request.applicationId = applicant.Application__c; //account ID
    request.setHeader(
      new Map<String, String>{
        'applicantId' => applicant.Id,
        'apiName' => 'SentiLinkIdCompletion'
      }
    );
    Test.setMock(
      HttpCalloutMock.class,
      new IdentityServiceMock('SentiLinkProvider', '400')
    );
    Test.startTest();
    ApexResponse response = IdentityController.identityVerify(request);
    Test.stopTest();
  }
}