force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactPointAddress/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and contact point address</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Contact Point Addresses</relationshipLabel>
    <relationshipName>ContactPointAddresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IdentityRepository.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Repository
 * @author Digital Align Team
 * @reference
 * @description
 **/
public with sharing class IdentityRepository extends DatabaseUtils {
  /**
   * @description
   * @author Digital Align Team | 11-01-2021
   * @param Id applicantId
   * @return Applicant__c
   **/
  public static Applicant__c readApplicantForIdentity(Id applicantId) {
    return (Applicant__c) DatabaseUtils.getRecord(
      new Query(Applicant__c.SObjectType)
        .addFields()
        .queryChild('dau01__ContactPointAddresses__r')
        .addFields()
        .removeFields('Address')
        .whereEq('IsPrimary', true)
        .orderBy('dau01__Order__c')
        .run()
        .whereEq('Id', applicantId)
        .toString()
    );
  }

  /**
   * @description read all applicant fields by ID without child objects
   * @author Digital Align | 11-01-2021
   * @param Id applicantId
   * @return Applicant__c
   **/
  public static Applicant__c fetchApplicantById(Id applicantId) {
    return (Applicant__c) getRecord(
      Query.newInstance(Applicant__c.SObjectType)
        .addFields()
        .whereEq('Id', applicantId)
        .toString(true)
    );
  }
}