force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant relation with application</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/EmailOtp__c.field-meta.xml
<CustomField>
    <fullName>EmailOtp__c</fullName>
    <description>To store Email Otp</description>
    <label>Email Otp</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/IdentificationDocument__c.field-meta.xml
<CustomField>
    <fullName>IdentificationDocument__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Object to store all identity details</description>
    <label>Identification Document</label>
    <referenceTo>FinServ__IdentificationDocument__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/OtpAttempts__c.field-meta.xml
<CustomField>
    <fullName>OtpAttempts__c</fullName>
    <description>To Store Otp Attempts</description>
    <label>Otp Attempts</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/OTPExpireTime__c.field-meta.xml
<CustomField>
    <fullName>OTPExpireTime__c</fullName>
    <description>OTP expire time</description>
    <inlineHelpText>OTP expire time</inlineHelpText>
    <label>OTP Expire Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SmsOtp__c.field-meta.xml
<CustomField>
    <fullName>SmsOtp__c</fullName>
    <description>To store OTP</description>
    <label>Sms OTP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/recordTypes/Primary.recordType-meta.xml
<RecordType>
    <fullName>Primary</fullName>
    <active>true</active>
    <description>Primary Applicant</description>
    <label>Primary</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>App{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationConfiguration__c/ApplicationConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Configuration</label>
</CustomObject>

force-app/main/default/objects/Employment__c/Employment__c.object-meta.xml
<CustomObject>
    <description
  >Represents information about a person&apos;s employment history.</description>
    <label>Employment</label>
    <nameField>
        <displayFormat>Emp-{00000}</displayFormat>
        <label>Employment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/FinServ__Employment__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__EmploymentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about a person&apos;s employment history.</description>
    <label>Employment</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant and Employment realtionship</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Employment</relationshipLabel>
    <relationshipName>Employments</relationshipName>
    <type>Lookup</type>
</CustomField>

fsc-app/main/default/objects/FinServ__IdentificationDocument__c/FinServ__IdentificationDocument__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >FinServ__IdentificationDocumentCompactLayout</compactLayoutAssignment>
    <description
  >Represents information about documents used to verify a person&apos;s identity.</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>DOC-{000000000}</displayFormat>
        <label>Document</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IdentificationDocument__c/IdentificationDocument__c.object-meta.xml
<CustomObject>
    <description>Identification Document for Applicants</description>
    <label>Identification Document</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identification Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IdentificationDocument__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>relationship between applicant and identification Documents</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Identification Documents</relationshipLabel>
    <relationshipName>IdentificationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/test/default/classes/ApplicantServiceTest.cls
@istest
public with sharing class ApplicantServiceTest {
  private static Application__c makeApplicationData() {
    Application__c acc = TestData.createApplication();
    acc = (Application__c) DatabaseUtils.insertRecord(acc);

    Applicant__c applicant = TestData.createApplicant('Primary');
    applicant.Application__c = acc.Id;
    applicant = (Applicant__c) DatabaseUtils.insertRecord(applicant);

    IdentificationDocument__c identity = TestData.createIdentity();
    identity.Applicant__c = applicant.Id;
    identity = (IdentificationDocument__c) DatabaseUtils.insertRecord(identity);
    applicant.mflow__IdentificationDocuments__r.addAll(new List<IdentificationDocument__c>{ identity });
    acc.Applicants__r.addAll(new List<Applicant__c>{ applicant });
    return acc;
  }
  private static Applicant__c makeApplicantData() {
    Application__c acc = TestData.createApplication();
    acc = (Application__c) DatabaseUtils.insertRecord(acc);
    Applicant__c applicant = TestData.createApplicant('Primary');
    applicant.Application__c = acc.Id;
    applicant.OTPExpireTime__c = Datetime.now();
    applicant.OtpAttempts__c = 1;
    applicant.SmsOtp__c = '0000';
    applicant.EmailOtp__c = '0000';
    applicant = (Applicant__c) DatabaseUtils.insertRecord(applicant);

    Employment__c employment = TestData.createEmployment();
    employment.Applicant__c = applicant.Id;
    employment = (Employment__c) DatabaseUtils.insertRecord(employment);
    applicant.mflow__Employments__r.addAll(new List<Employment__c>{ employment });

    return applicant;
  }
  private static ApplicationConfiguration__c makeApplicationConfiguration() {
    ApplicationConfiguration__c appConfig = TestData.createApplicationConfiguration();
    appConfig = (ApplicationConfiguration__c) DatabaseUtils.insertRecord(appConfig);
    return appConfig;
  }
  @isTest
  static void applicantListTest() {
    makeApplicationConfiguration();
    Application__c application = makeApplicationData();
    ApexRequest request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'applicantIds' => application.applicants__r });
    request.setData(application.applicants__r);
    test.startTest();
    ApplicantController.saveApplicants(request);
    test.stopTest();
  }
  @isTest
  static void singleApplicantTest() {
    makeApplicationConfiguration();
    Application__c application = makeApplicationData();
    Applicant__c applicant = makeApplicantData();
    ApexRequest request = new ApexRequest();
    request.setHeader(
      new Map<String, object>{
        'applicantIds' => new List<Applicant__c>{ applicant, applicant },
        'applicantId' => applicant.Id,
        'otpMode' => 'SMS;EMAIL',
        'sms' => '0000',
        'email' => '0000'
      }
    );
    request.setData(new Applicant__c());
    test.startTest();
    ApplicantController.readApplicantsWithChild(request);
    ApplicantController.saveApplicant(request);
    ApplicantController.generateOTP(request);
    ApplicantController.validateOTP(request);
    test.stopTest();
  }
  @isTest
  static void singleApplicantTestTwo() {
    makeApplicationConfiguration();
    Application__c application = makeApplicationData();
    Applicant__c applicant = makeApplicantData();
    ApexRequest request = new ApexRequest();
    request.setHeader(
      new Map<String, object>{
        'applicantIds' => new List<Applicant__c>{ applicant, applicant },
        'applicantId' => applicant.Id,
        'otpMode' => 'SMS;EMAIL',
        'sms' => '0000',
        'email' => '0000'
      }
    );
    request.setData(new Applicant__c());
    test.startTest();
    try {
      ApplicantController.readApplicantsWithChild(new ApexRequest());
      ApplicantController.saveApplicant(new ApexRequest());
      ApplicantController.generateOTP(new ApexRequest());
      ApplicantController.validateOTP(new ApexRequest());
    } catch (Exception e) {
    }
    test.stopTest();
  }
  @isTest
  static void exceptionTest() {
    Application__c application = makeApplicationData();
    ApexRequest request = new ApexRequest();
    request.setHeader(new Map<String, object>{ 'applicantIds' => application.applicants__r });
    request.setData(application.applicants__r);
    test.startTest();
    ApplicantController.atomicAuthenticate(request);
    ApplicantController.getAtomicResponse(request);
    ApplicantController.generatePaySlipsW2(request);
    test.stopTest();
  }
}