force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/OTPExpireTime__c.field-meta.xml
<CustomField>
    <fullName>OTPExpireTime__c</fullName>
    <description>OTP expire time</description>
    <inlineHelpText>OTP expire time</inlineHelpText>
    <label>OTP Expire Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SmsOtp__c.field-meta.xml
<CustomField>
    <fullName>SmsOtp__c</fullName>
    <description>To store OTP</description>
    <label>Sms OTP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/SmsOtpAttempts__c.field-meta.xml
<CustomField>
    <fullName>SmsOtpAttempts__c</fullName>
    <description>Number of OTP retry Attempts</description>
    <label>OTPAttempts</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApplicationConfiguration__c/ApplicationConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Configuration</label>
</CustomObject>

force-app/main/default/objects/ApplicationConfiguration__c/fields/OTPExpirationTime__c.field-meta.xml
<CustomField>
    <fullName>OTPExpirationTime__c</fullName>
    <description>OTP Expiration Time</description>
    <label>OTPExpirationTime</label>
    <type>Number</type>
    <scale>0</scale>
    <precision>4</precision>
</CustomField>

force-app/main/default/classes/NotificationService.cls
/**
 * Copyright (c) 2021 Digital Align
 * @group Service
 * @author Digital Align Team
 * @reference
 * @description NotificationService for sending messages
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global virtual with sharing class NotificationService extends AbstractService {
  @TestVisible
  private static NotificationService serviceInstance;

  public NotificationService() {
    super(NotificationService.class);
  }

  /**
   * @description Provides a singleton instance of NotificationService from which all other class methods can be accessed.
   * @author Digital Align Team | 07-22-2021
   * @return Object  singleton
   **/
  public static NotificationService getInstance() {
    if (serviceInstance == null) {
      serviceInstance = (NotificationService) getInstance(
        NotificationService.class
      );
    }
    return serviceInstance;
  }

  /**
   * @description  Method to send OTP message to phone.
   * @author Digital Align Team | 11-03-2021
   * @param Map<String Object> params
   * @return virtual
   **/
  global virtual object sendOTPMessage(Map<String, Object> params) {
    Flow.initialize(ApexRequest.getApplicationId());
    Flow.setFlow('EligibilityFlow');
    Flow.setSubFlow(APINames.TwillioMessaging.name());
    try {
      Applicant__c applicant = NotificationRepository.fetchApplicantById(
        (string) params.get('ApplicantId')
      );
      String message;
      Integer otp = Math.round((Math.random() * (9000) + 1000));
      params.put('toPhone', applicant.Phone__c);
      params.put('otp', otp);

      if (HttpBuilder.isActiveApiSetting(APINames.TwillioMessaging)) {
        HttpBuilder.setAPISetting(APINames.TwillioMessaging);
        HttpBuilder.replaceEndpoint(
          '{Twillio_Account}',
          HttpBuilder.getApiConstant('Twillio_Account')
        );
        HttpBuilder.replaceEndpoint(
          '{Version}',
          HttpBuilder.getApiConstant('Version')
        );
        log?.debug('Endpoint :' + HttpBuilder.getAPISetting());
        HttpBuilder.Response response = TwillioProvider.getInstance()
          .sendMessageUsingTwillio(params);

        applicant.SmsOtp__c = otp;
        applicant.SmsOtpAttempts__c = 0;
        applicant.OTPExpireTime__c = Datetime.now()
          .addMinutes(
            (Integer) ApplicationConfiguration__c.getOrgDefaults()
              .OTPExpirationTime__c
          );
        NotificationRepository.updateRecord(applicant);
        flow.setSubFlowPassed(response.status);
        flow.setFlowPassed('Completed');
        return true;
      } else {
        throw new CustomException('Requested API is disabled');
      }
    } catch (Exception ex) {
      flow.setSubFlowFailed(ex.getMessage());
      flow.setFlowFailed('Failed');
      throw ex;
    }
  }
}