force-app/main/default/objects/DynamicDataTable__mdt/DynamicDataTable__mdt.object-meta.xml
<CustomObject>
    <description
  >Dynamic metadata table for getting custom fields from the object for data table</description>
    <label>DynamicDataTable</label>
    <pluralLabel>DynamicDataTables</pluralLabel>
</CustomObject>

force-app/main/default/objects/DynamicDataTableItem__mdt/DynamicDataTableItem__mdt.object-meta.xml
<CustomObject>
    <description>Dynamic data table fields based on the label selected</description>
    <label>DynamicDataTableItem</label>
    <pluralLabel>DynamicDataTableItems</pluralLabel>
</CustomObject>

force-app/main/default/objects/DynamicDataTableItem__mdt/fields/DynamicDataTable__c.field-meta.xml
<CustomField>
    <fullName>DynamicDataTable__c</fullName>
    <description
  >Master table to list the layout name or data table name</description>
    <label>DynamicDataTable</label>
    <referenceTo>DynamicDataTable__mdt</referenceTo>
    <relationshipLabel>DynamicDataTableItems</relationshipLabel>
    <relationshipName>DynamicDataTableItems</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/DynamicLWCDataTable/DynamicLWCDataTableRepository.cls
public with sharing class DynamicLWCDataTableRepository {
  public static List<DynamicDataTable__mdt> getTableDetails(
    String metaDataName,
    String FilterString,
    String SortString
  ) {
    List<DynamicDataTable__mdt> returnObjectList = new List<DynamicDataTable__mdt>();
    try {
      String queryString = new Query(DynamicDataTable__mdt.SObjectType)
        .addFields()
        .queryChild('dau01__DynamicDataTableItems__r')
        .addFields()
        .orderBy('dau01__DisplayOrder__c')
        .run()
        .run()
        .whereEq('dau01__DynamicDataTable__mdt.DeveloperName', metaDataName)
        .toString(true);

      return returnObjectList = (List<DynamicDataTable__mdt>) DatabaseUtils.getRecords(
        queryString,
        new List<Object>{ metaDataName }
      );
    } catch (exception ex) {
      throw ex;
    }
  }
}